/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Account.def
	public class EntityBaseEntityCall_AccountBase : EntityCall
	{

		public EntityBaseEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void reqAvatarList()
		{
			Bundle pBundle = newCall("reqAvatarList", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void reqCreateAvatar(Byte arg1, string arg2)
		{
			Bundle pBundle = newCall("reqCreateAvatar", 0);
			if(pBundle == null)
				return;

			bundle.writeUint8(arg1);
			bundle.writeUnicode(arg2);
			sendCall(null);
		}

		public void reqRemoveAvatar(string arg1)
		{
			Bundle pBundle = newCall("reqRemoveAvatar", 0);
			if(pBundle == null)
				return;

			bundle.writeUnicode(arg1);
			sendCall(null);
		}

		public void reqRemoveAvatarDBID(UInt64 arg1)
		{
			Bundle pBundle = newCall("reqRemoveAvatarDBID", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

		public void selectAvatarGame(UInt64 arg1)
		{
			Bundle pBundle = newCall("selectAvatarGame", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AccountBase : EntityCall
	{

		public EntityCellEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
