/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Test.def
	public class EntityBaseEntityCall_TestBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityBaseEntityCall_TestBase(UInt16 ecpID, Int32 eid) : base(eid, "Test")
		{
			entityComponentPropertyID = ecpID;
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void say(Int32 arg1)
		{
			Bundle pBundle = newCall("say", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_TestBase : EntityCall
	{
		public UInt16 entityComponentPropertyID = 0;

		public EntityCellEntityCall_TestBase(UInt16 ecpID, Int32 eid) : base(eid, "Test")
		{
			entityComponentPropertyID = ecpID;
			className = "Test";
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void hello(Int32 arg1)
		{
			Bundle pBundle = newCall("hello", entityComponentPropertyID);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

	}
	}
