/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_lastSelCharacter = new Property();
			pAccount_lastSelCharacter.name = "lastSelCharacter";
			pAccount_lastSelCharacter.properUtype = 2;
			pAccount_lastSelCharacter.properFlags = 32;
			pAccount_lastSelCharacter.aliasID = 4;
			UInt64 Account_lastSelCharacter_defval;
			UInt64.TryParse("0", out Account_lastSelCharacter_defval);
			pAccount_lastSelCharacter.defaultVal = Account_lastSelCharacter_defval;
			pAccountModule.propertys["lastSelCharacter"] = pAccount_lastSelCharacter; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_lastSelCharacter.aliasID] = pAccount_lastSelCharacter;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(lastSelCharacter / 2).");

			List<DATATYPE_BASE> pAccount_onCreateAvatarResult_args = new List<DATATYPE_BASE>();
			pAccount_onCreateAvatarResult_args.Add(EntityDef.id2datatypes[2]);
			pAccount_onCreateAvatarResult_args.Add(EntityDef.id2datatypes[25]);

			Method pAccount_onCreateAvatarResult = new Method();
			pAccount_onCreateAvatarResult.name = "onCreateAvatarResult";
			pAccount_onCreateAvatarResult.methodUtype = 10005;
			pAccount_onCreateAvatarResult.aliasID = 1;
			pAccount_onCreateAvatarResult.args = pAccount_onCreateAvatarResult_args;

			pAccountModule.methods["onCreateAvatarResult"] = pAccount_onCreateAvatarResult; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onCreateAvatarResult.aliasID] = pAccount_onCreateAvatarResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onCreateAvatarResult / 10005).");

			List<DATATYPE_BASE> pAccount_onRemoveAvatar_args = new List<DATATYPE_BASE>();
			pAccount_onRemoveAvatar_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_onRemoveAvatar = new Method();
			pAccount_onRemoveAvatar.name = "onRemoveAvatar";
			pAccount_onRemoveAvatar.methodUtype = 3;
			pAccount_onRemoveAvatar.aliasID = 2;
			pAccount_onRemoveAvatar.args = pAccount_onRemoveAvatar_args;

			pAccountModule.methods["onRemoveAvatar"] = pAccount_onRemoveAvatar; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onRemoveAvatar.aliasID] = pAccount_onRemoveAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onRemoveAvatar / 3).");

			List<DATATYPE_BASE> pAccount_onReqAvatarList_args = new List<DATATYPE_BASE>();
			pAccount_onReqAvatarList_args.Add(EntityDef.id2datatypes[26]);

			Method pAccount_onReqAvatarList = new Method();
			pAccount_onReqAvatarList.name = "onReqAvatarList";
			pAccount_onReqAvatarList.methodUtype = 10003;
			pAccount_onReqAvatarList.aliasID = 3;
			pAccount_onReqAvatarList.args = pAccount_onReqAvatarList_args;

			pAccountModule.methods["onReqAvatarList"] = pAccount_onReqAvatarList; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqAvatarList.aliasID] = pAccount_onReqAvatarList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqAvatarList / 10003).");

			List<DATATYPE_BASE> pAccount_reqAvatarList_args = new List<DATATYPE_BASE>();

			Method pAccount_reqAvatarList = new Method();
			pAccount_reqAvatarList.name = "reqAvatarList";
			pAccount_reqAvatarList.methodUtype = 10001;
			pAccount_reqAvatarList.aliasID = -1;
			pAccount_reqAvatarList.args = pAccount_reqAvatarList_args;

			pAccountModule.methods["reqAvatarList"] = pAccount_reqAvatarList; 
			pAccountModule.base_methods["reqAvatarList"] = pAccount_reqAvatarList;

			pAccountModule.idbase_methods[pAccount_reqAvatarList.methodUtype] = pAccount_reqAvatarList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqAvatarList / 10001).");

			List<DATATYPE_BASE> pAccount_reqCreateAvatar_args = new List<DATATYPE_BASE>();
			pAccount_reqCreateAvatar_args.Add(EntityDef.id2datatypes[2]);
			pAccount_reqCreateAvatar_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqCreateAvatar = new Method();
			pAccount_reqCreateAvatar.name = "reqCreateAvatar";
			pAccount_reqCreateAvatar.methodUtype = 10002;
			pAccount_reqCreateAvatar.aliasID = -1;
			pAccount_reqCreateAvatar.args = pAccount_reqCreateAvatar_args;

			pAccountModule.methods["reqCreateAvatar"] = pAccount_reqCreateAvatar; 
			pAccountModule.base_methods["reqCreateAvatar"] = pAccount_reqCreateAvatar;

			pAccountModule.idbase_methods[pAccount_reqCreateAvatar.methodUtype] = pAccount_reqCreateAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqCreateAvatar / 10002).");

			List<DATATYPE_BASE> pAccount_reqRemoveAvatar_args = new List<DATATYPE_BASE>();
			pAccount_reqRemoveAvatar_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqRemoveAvatar = new Method();
			pAccount_reqRemoveAvatar.name = "reqRemoveAvatar";
			pAccount_reqRemoveAvatar.methodUtype = 1;
			pAccount_reqRemoveAvatar.aliasID = -1;
			pAccount_reqRemoveAvatar.args = pAccount_reqRemoveAvatar_args;

			pAccountModule.methods["reqRemoveAvatar"] = pAccount_reqRemoveAvatar; 
			pAccountModule.base_methods["reqRemoveAvatar"] = pAccount_reqRemoveAvatar;

			pAccountModule.idbase_methods[pAccount_reqRemoveAvatar.methodUtype] = pAccount_reqRemoveAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqRemoveAvatar / 1).");

			List<DATATYPE_BASE> pAccount_reqRemoveAvatarDBID_args = new List<DATATYPE_BASE>();
			pAccount_reqRemoveAvatarDBID_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_reqRemoveAvatarDBID = new Method();
			pAccount_reqRemoveAvatarDBID.name = "reqRemoveAvatarDBID";
			pAccount_reqRemoveAvatarDBID.methodUtype = 2;
			pAccount_reqRemoveAvatarDBID.aliasID = -1;
			pAccount_reqRemoveAvatarDBID.args = pAccount_reqRemoveAvatarDBID_args;

			pAccountModule.methods["reqRemoveAvatarDBID"] = pAccount_reqRemoveAvatarDBID; 
			pAccountModule.base_methods["reqRemoveAvatarDBID"] = pAccount_reqRemoveAvatarDBID;

			pAccountModule.idbase_methods[pAccount_reqRemoveAvatarDBID.methodUtype] = pAccount_reqRemoveAvatarDBID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqRemoveAvatarDBID / 2).");

			List<DATATYPE_BASE> pAccount_selectAvatarGame_args = new List<DATATYPE_BASE>();
			pAccount_selectAvatarGame_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_selectAvatarGame = new Method();
			pAccount_selectAvatarGame.name = "selectAvatarGame";
			pAccount_selectAvatarGame.methodUtype = 10004;
			pAccount_selectAvatarGame.aliasID = -1;
			pAccount_selectAvatarGame.args = pAccount_selectAvatarGame_args;

			pAccountModule.methods["selectAvatarGame"] = pAccount_selectAvatarGame; 
			pAccountModule.base_methods["selectAvatarGame"] = pAccount_selectAvatarGame;

			pAccountModule.idbase_methods[pAccount_selectAvatarGame.methodUtype] = pAccount_selectAvatarGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(selectAvatarGame / 10004).");

			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[2] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 1;
			Vector3 Avatar_position_defval = new Vector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 2;
			Vector3 Avatar_direction_defval = new Vector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 3;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_HP = new Property();
			pAvatar_HP.name = "HP";
			pAvatar_HP.properUtype = 47001;
			pAvatar_HP.properFlags = 4;
			pAvatar_HP.aliasID = 4;
			Int32 Avatar_HP_defval;
			Int32.TryParse("0", out Avatar_HP_defval);
			pAvatar_HP.defaultVal = Avatar_HP_defval;
			pAvatarModule.propertys["HP"] = pAvatar_HP; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_HP.aliasID] = pAvatar_HP;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(HP / 47001).");

			Property pAvatar_HP_Max = new Property();
			pAvatar_HP_Max.name = "HP_Max";
			pAvatar_HP_Max.properUtype = 47002;
			pAvatar_HP_Max.properFlags = 4;
			pAvatar_HP_Max.aliasID = 5;
			Int32 Avatar_HP_Max_defval;
			Int32.TryParse("0", out Avatar_HP_Max_defval);
			pAvatar_HP_Max.defaultVal = Avatar_HP_Max_defval;
			pAvatarModule.propertys["HP_Max"] = pAvatar_HP_Max; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_HP_Max.aliasID] = pAvatar_HP_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(HP_Max / 47002).");

			Property pAvatar_MP = new Property();
			pAvatar_MP.name = "MP";
			pAvatar_MP.properUtype = 47003;
			pAvatar_MP.properFlags = 4;
			pAvatar_MP.aliasID = 6;
			Int32 Avatar_MP_defval;
			Int32.TryParse("0", out Avatar_MP_defval);
			pAvatar_MP.defaultVal = Avatar_MP_defval;
			pAvatarModule.propertys["MP"] = pAvatar_MP; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_MP.aliasID] = pAvatar_MP;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(MP / 47003).");

			Property pAvatar_MP_Max = new Property();
			pAvatar_MP_Max.name = "MP_Max";
			pAvatar_MP_Max.properUtype = 47004;
			pAvatar_MP_Max.properFlags = 4;
			pAvatar_MP_Max.aliasID = 7;
			Int32 Avatar_MP_Max_defval;
			Int32.TryParse("0", out Avatar_MP_Max_defval);
			pAvatar_MP_Max.defaultVal = Avatar_MP_Max_defval;
			pAvatarModule.propertys["MP_Max"] = pAvatar_MP_Max; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_MP_Max.aliasID] = pAvatar_MP_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(MP_Max / 47004).");

			Property pAvatar_component1 = new Property();
			pAvatar_component1.name = "component1";
			pAvatar_component1.properUtype = 16;
			pAvatar_component1.properFlags = 253;
			pAvatar_component1.aliasID = 8;
			pAvatarModule.propertys["component1"] = pAvatar_component1; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_component1.aliasID] = pAvatar_component1;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(component1 / 16).");

			Property pAvatar_component2 = new Property();
			pAvatar_component2.name = "component2";
			pAvatar_component2.properUtype = 21;
			pAvatar_component2.properFlags = 97;
			pAvatar_component2.aliasID = 9;
			pAvatarModule.propertys["component2"] = pAvatar_component2; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_component2.aliasID] = pAvatar_component2;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(component2 / 21).");

			Property pAvatar_component3 = new Property();
			pAvatar_component3.name = "component3";
			pAvatar_component3.properUtype = 22;
			pAvatar_component3.properFlags = 157;
			pAvatar_component3.aliasID = 10;
			pAvatarModule.propertys["component3"] = pAvatar_component3; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_component3.aliasID] = pAvatar_component3;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(component3 / 22).");

			Property pAvatar_forbids = new Property();
			pAvatar_forbids.name = "forbids";
			pAvatar_forbids.properUtype = 47005;
			pAvatar_forbids.properFlags = 4;
			pAvatar_forbids.aliasID = 11;
			Int32 Avatar_forbids_defval;
			Int32.TryParse("0", out Avatar_forbids_defval);
			pAvatar_forbids.defaultVal = Avatar_forbids_defval;
			pAvatarModule.propertys["forbids"] = pAvatar_forbids; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_forbids.aliasID] = pAvatar_forbids;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(forbids / 47005).");

			Property pAvatar_level = new Property();
			pAvatar_level.name = "level";
			pAvatar_level.properUtype = 41002;
			pAvatar_level.properFlags = 8;
			pAvatar_level.aliasID = 12;
			UInt16 Avatar_level_defval;
			UInt16.TryParse("", out Avatar_level_defval);
			pAvatar_level.defaultVal = Avatar_level_defval;
			pAvatarModule.propertys["level"] = pAvatar_level; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_level.aliasID] = pAvatar_level;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(level / 41002).");

			Property pAvatar_modelID = new Property();
			pAvatar_modelID.name = "modelID";
			pAvatar_modelID.properUtype = 41006;
			pAvatar_modelID.properFlags = 4;
			pAvatar_modelID.aliasID = 13;
			UInt32 Avatar_modelID_defval;
			UInt32.TryParse("0", out Avatar_modelID_defval);
			pAvatar_modelID.defaultVal = Avatar_modelID_defval;
			pAvatarModule.propertys["modelID"] = pAvatar_modelID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_modelID.aliasID] = pAvatar_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(modelID / 41006).");

			Property pAvatar_modelScale = new Property();
			pAvatar_modelScale.name = "modelScale";
			pAvatar_modelScale.properUtype = 41007;
			pAvatar_modelScale.properFlags = 4;
			pAvatar_modelScale.aliasID = 14;
			Byte Avatar_modelScale_defval;
			Byte.TryParse("30", out Avatar_modelScale_defval);
			pAvatar_modelScale.defaultVal = Avatar_modelScale_defval;
			pAvatarModule.propertys["modelScale"] = pAvatar_modelScale; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_modelScale.aliasID] = pAvatar_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(modelScale / 41007).");

			Property pAvatar_moveSpeed = new Property();
			pAvatar_moveSpeed.name = "moveSpeed";
			pAvatar_moveSpeed.properUtype = 11;
			pAvatar_moveSpeed.properFlags = 4;
			pAvatar_moveSpeed.aliasID = 15;
			Byte Avatar_moveSpeed_defval;
			Byte.TryParse("50", out Avatar_moveSpeed_defval);
			pAvatar_moveSpeed.defaultVal = Avatar_moveSpeed_defval;
			pAvatarModule.propertys["moveSpeed"] = pAvatar_moveSpeed; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_moveSpeed.aliasID] = pAvatar_moveSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(moveSpeed / 11).");

			Property pAvatar_name = new Property();
			pAvatar_name.name = "name";
			pAvatar_name.properUtype = 41003;
			pAvatar_name.properFlags = 4;
			pAvatar_name.aliasID = 16;
			string Avatar_name_defval = "";
			pAvatar_name.defaultVal = Avatar_name_defval;
			pAvatarModule.propertys["name"] = pAvatar_name; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_name.aliasID] = pAvatar_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(name / 41003).");

			Property pAvatar_own_val = new Property();
			pAvatar_own_val.name = "own_val";
			pAvatar_own_val.properUtype = 6;
			pAvatar_own_val.properFlags = 16;
			pAvatar_own_val.aliasID = 17;
			UInt16 Avatar_own_val_defval;
			UInt16.TryParse("", out Avatar_own_val_defval);
			pAvatar_own_val.defaultVal = Avatar_own_val_defval;
			pAvatarModule.propertys["own_val"] = pAvatar_own_val; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_own_val.aliasID] = pAvatar_own_val;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(own_val / 6).");

			Property pAvatar_spaceUType = new Property();
			pAvatar_spaceUType.name = "spaceUType";
			pAvatar_spaceUType.properUtype = 41001;
			pAvatar_spaceUType.properFlags = 8;
			pAvatar_spaceUType.aliasID = 18;
			UInt32 Avatar_spaceUType_defval;
			UInt32.TryParse("", out Avatar_spaceUType_defval);
			pAvatar_spaceUType.defaultVal = Avatar_spaceUType_defval;
			pAvatarModule.propertys["spaceUType"] = pAvatar_spaceUType; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceUType.aliasID] = pAvatar_spaceUType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceUType / 41001).");

			Property pAvatar_state = new Property();
			pAvatar_state.name = "state";
			pAvatar_state.properUtype = 47006;
			pAvatar_state.properFlags = 4;
			pAvatar_state.aliasID = 19;
			SByte Avatar_state_defval;
			SByte.TryParse("0", out Avatar_state_defval);
			pAvatar_state.defaultVal = Avatar_state_defval;
			pAvatarModule.propertys["state"] = pAvatar_state; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_state.aliasID] = pAvatar_state;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(state / 47006).");

			Property pAvatar_subState = new Property();
			pAvatar_subState.name = "subState";
			pAvatar_subState.properUtype = 47007;
			pAvatar_subState.properFlags = 4;
			pAvatar_subState.aliasID = 20;
			Byte Avatar_subState_defval;
			Byte.TryParse("", out Avatar_subState_defval);
			pAvatar_subState.defaultVal = Avatar_subState_defval;
			pAvatarModule.propertys["subState"] = pAvatar_subState; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_subState.aliasID] = pAvatar_subState;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(subState / 47007).");

			Property pAvatar_uid = new Property();
			pAvatar_uid.name = "uid";
			pAvatar_uid.properUtype = 41004;
			pAvatar_uid.properFlags = 4;
			pAvatar_uid.aliasID = 21;
			UInt32 Avatar_uid_defval;
			UInt32.TryParse("0", out Avatar_uid_defval);
			pAvatar_uid.defaultVal = Avatar_uid_defval;
			pAvatarModule.propertys["uid"] = pAvatar_uid; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_uid.aliasID] = pAvatar_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(uid / 41004).");

			Property pAvatar_utype = new Property();
			pAvatar_utype.name = "utype";
			pAvatar_utype.properUtype = 41005;
			pAvatar_utype.properFlags = 4;
			pAvatar_utype.aliasID = 22;
			UInt32 Avatar_utype_defval;
			UInt32.TryParse("0", out Avatar_utype_defval);
			pAvatar_utype.defaultVal = Avatar_utype_defval;
			pAvatarModule.propertys["utype"] = pAvatar_utype; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_utype.aliasID] = pAvatar_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(utype / 41005).");

			List<DATATYPE_BASE> pAvatar_dialog_addOption_args = new List<DATATYPE_BASE>();
			pAvatar_dialog_addOption_args.Add(EntityDef.id2datatypes[2]);
			pAvatar_dialog_addOption_args.Add(EntityDef.id2datatypes[4]);
			pAvatar_dialog_addOption_args.Add(EntityDef.id2datatypes[12]);
			pAvatar_dialog_addOption_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_dialog_addOption = new Method();
			pAvatar_dialog_addOption.name = "dialog_addOption";
			pAvatar_dialog_addOption.methodUtype = 10101;
			pAvatar_dialog_addOption.aliasID = 1;
			pAvatar_dialog_addOption.args = pAvatar_dialog_addOption_args;

			pAvatarModule.methods["dialog_addOption"] = pAvatar_dialog_addOption; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_dialog_addOption.aliasID] = pAvatar_dialog_addOption;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(dialog_addOption / 10101).");

			List<DATATYPE_BASE> pAvatar_dialog_close_args = new List<DATATYPE_BASE>();

			Method pAvatar_dialog_close = new Method();
			pAvatar_dialog_close.name = "dialog_close";
			pAvatar_dialog_close.methodUtype = 10104;
			pAvatar_dialog_close.aliasID = 2;
			pAvatar_dialog_close.args = pAvatar_dialog_close_args;

			pAvatarModule.methods["dialog_close"] = pAvatar_dialog_close; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_dialog_close.aliasID] = pAvatar_dialog_close;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(dialog_close / 10104).");

			List<DATATYPE_BASE> pAvatar_dialog_setText_args = new List<DATATYPE_BASE>();
			pAvatar_dialog_setText_args.Add(EntityDef.id2datatypes[12]);
			pAvatar_dialog_setText_args.Add(EntityDef.id2datatypes[2]);
			pAvatar_dialog_setText_args.Add(EntityDef.id2datatypes[4]);
			pAvatar_dialog_setText_args.Add(EntityDef.id2datatypes[12]);

			Method pAvatar_dialog_setText = new Method();
			pAvatar_dialog_setText.name = "dialog_setText";
			pAvatar_dialog_setText.methodUtype = 10102;
			pAvatar_dialog_setText.aliasID = 3;
			pAvatar_dialog_setText.args = pAvatar_dialog_setText_args;

			pAvatarModule.methods["dialog_setText"] = pAvatar_dialog_setText; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_dialog_setText.aliasID] = pAvatar_dialog_setText;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(dialog_setText / 10102).");

			List<DATATYPE_BASE> pAvatar_onAddSkill_args = new List<DATATYPE_BASE>();
			pAvatar_onAddSkill_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onAddSkill = new Method();
			pAvatar_onAddSkill.name = "onAddSkill";
			pAvatar_onAddSkill.methodUtype = 12;
			pAvatar_onAddSkill.aliasID = 4;
			pAvatar_onAddSkill.args = pAvatar_onAddSkill_args;

			pAvatarModule.methods["onAddSkill"] = pAvatar_onAddSkill; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onAddSkill.aliasID] = pAvatar_onAddSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onAddSkill / 12).");

			List<DATATYPE_BASE> pAvatar_onJump_args = new List<DATATYPE_BASE>();

			Method pAvatar_onJump = new Method();
			pAvatar_onJump.name = "onJump";
			pAvatar_onJump.methodUtype = 7;
			pAvatar_onJump.aliasID = 5;
			pAvatar_onJump.args = pAvatar_onJump_args;

			pAvatarModule.methods["onJump"] = pAvatar_onJump; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onJump.aliasID] = pAvatar_onJump;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onJump / 7).");

			List<DATATYPE_BASE> pAvatar_onRemoveSkill_args = new List<DATATYPE_BASE>();
			pAvatar_onRemoveSkill_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_onRemoveSkill = new Method();
			pAvatar_onRemoveSkill.name = "onRemoveSkill";
			pAvatar_onRemoveSkill.methodUtype = 13;
			pAvatar_onRemoveSkill.aliasID = 6;
			pAvatar_onRemoveSkill.args = pAvatar_onRemoveSkill_args;

			pAvatarModule.methods["onRemoveSkill"] = pAvatar_onRemoveSkill; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onRemoveSkill.aliasID] = pAvatar_onRemoveSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onRemoveSkill / 13).");

			List<DATATYPE_BASE> pAvatar_recvDamage_args = new List<DATATYPE_BASE>();
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_recvDamage = new Method();
			pAvatar_recvDamage.name = "recvDamage";
			pAvatar_recvDamage.methodUtype = 16;
			pAvatar_recvDamage.aliasID = 7;
			pAvatar_recvDamage.args = pAvatar_recvDamage_args;

			pAvatarModule.methods["recvDamage"] = pAvatar_recvDamage; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_recvDamage.aliasID] = pAvatar_recvDamage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(recvDamage / 16).");

			List<DATATYPE_BASE> pAvatar_dialog_args = new List<DATATYPE_BASE>();
			pAvatar_dialog_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_dialog_args.Add(EntityDef.id2datatypes[4]);

			Method pAvatar_dialog = new Method();
			pAvatar_dialog.name = "dialog";
			pAvatar_dialog.methodUtype = 11003;
			pAvatar_dialog.aliasID = -1;
			pAvatar_dialog.args = pAvatar_dialog_args;

			pAvatarModule.methods["dialog"] = pAvatar_dialog; 
			pAvatarModule.cell_methods["dialog"] = pAvatar_dialog;

			pAvatarModule.idcell_methods[pAvatar_dialog.methodUtype] = pAvatar_dialog;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(dialog / 11003).");

			List<DATATYPE_BASE> pAvatar_jump_args = new List<DATATYPE_BASE>();

			Method pAvatar_jump = new Method();
			pAvatar_jump.name = "jump";
			pAvatar_jump.methodUtype = 5;
			pAvatar_jump.aliasID = -1;
			pAvatar_jump.args = pAvatar_jump_args;

			pAvatarModule.methods["jump"] = pAvatar_jump; 
			pAvatarModule.cell_methods["jump"] = pAvatar_jump;

			pAvatarModule.idcell_methods[pAvatar_jump.methodUtype] = pAvatar_jump;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(jump / 5).");

			List<DATATYPE_BASE> pAvatar_relive_args = new List<DATATYPE_BASE>();
			pAvatar_relive_args.Add(EntityDef.id2datatypes[2]);

			Method pAvatar_relive = new Method();
			pAvatar_relive.name = "relive";
			pAvatar_relive.methodUtype = 4;
			pAvatar_relive.aliasID = -1;
			pAvatar_relive.args = pAvatar_relive_args;

			pAvatarModule.methods["relive"] = pAvatar_relive; 
			pAvatarModule.cell_methods["relive"] = pAvatar_relive;

			pAvatarModule.idcell_methods[pAvatar_relive.methodUtype] = pAvatar_relive;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(relive / 4).");

			List<DATATYPE_BASE> pAvatar_requestPull_args = new List<DATATYPE_BASE>();

			Method pAvatar_requestPull = new Method();
			pAvatar_requestPull.name = "requestPull";
			pAvatar_requestPull.methodUtype = 11;
			pAvatar_requestPull.aliasID = -1;
			pAvatar_requestPull.args = pAvatar_requestPull_args;

			pAvatarModule.methods["requestPull"] = pAvatar_requestPull; 
			pAvatarModule.cell_methods["requestPull"] = pAvatar_requestPull;

			pAvatarModule.idcell_methods[pAvatar_requestPull.methodUtype] = pAvatar_requestPull;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(requestPull / 11).");

			List<DATATYPE_BASE> pAvatar_useTargetSkill_args = new List<DATATYPE_BASE>();
			pAvatar_useTargetSkill_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_useTargetSkill_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_useTargetSkill = new Method();
			pAvatar_useTargetSkill.name = "useTargetSkill";
			pAvatar_useTargetSkill.methodUtype = 11001;
			pAvatar_useTargetSkill.aliasID = -1;
			pAvatar_useTargetSkill.args = pAvatar_useTargetSkill_args;

			pAvatarModule.methods["useTargetSkill"] = pAvatar_useTargetSkill; 
			pAvatarModule.cell_methods["useTargetSkill"] = pAvatar_useTargetSkill;

			pAvatarModule.idcell_methods[pAvatar_useTargetSkill.methodUtype] = pAvatar_useTargetSkill;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(useTargetSkill / 11001).");

			ScriptModule pTestModule = new ScriptModule("Test");
			EntityDef.moduledefs["Test"] = pTestModule;
			EntityDef.idmoduledefs[3] = pTestModule;

			Property pTest_position = new Property();
			pTest_position.name = "position";
			pTest_position.properUtype = 40000;
			pTest_position.properFlags = 4;
			pTest_position.aliasID = 1;
			Vector3 Test_position_defval = new Vector3();
			pTest_position.defaultVal = Test_position_defval;
			pTestModule.propertys["position"] = pTest_position; 

			pTestModule.usePropertyDescrAlias = true;
			pTestModule.idpropertys[(UInt16)pTest_position.aliasID] = pTest_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Test), property(position / 40000).");

			Property pTest_direction = new Property();
			pTest_direction.name = "direction";
			pTest_direction.properUtype = 40001;
			pTest_direction.properFlags = 4;
			pTest_direction.aliasID = 2;
			Vector3 Test_direction_defval = new Vector3();
			pTest_direction.defaultVal = Test_direction_defval;
			pTestModule.propertys["direction"] = pTest_direction; 

			pTestModule.usePropertyDescrAlias = true;
			pTestModule.idpropertys[(UInt16)pTest_direction.aliasID] = pTest_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Test), property(direction / 40001).");

			Property pTest_spaceID = new Property();
			pTest_spaceID.name = "spaceID";
			pTest_spaceID.properUtype = 40002;
			pTest_spaceID.properFlags = 16;
			pTest_spaceID.aliasID = 3;
			UInt32 Test_spaceID_defval;
			UInt32.TryParse("", out Test_spaceID_defval);
			pTest_spaceID.defaultVal = Test_spaceID_defval;
			pTestModule.propertys["spaceID"] = pTest_spaceID; 

			pTestModule.usePropertyDescrAlias = true;
			pTestModule.idpropertys[(UInt16)pTest_spaceID.aliasID] = pTest_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Test), property(spaceID / 40002).");

			Property pTest_own = new Property();
			pTest_own.name = "own";
			pTest_own.properUtype = 18;
			pTest_own.properFlags = 8;
			pTest_own.aliasID = 4;
			Int32 Test_own_defval;
			Int32.TryParse("1001", out Test_own_defval);
			pTest_own.defaultVal = Test_own_defval;
			pTestModule.propertys["own"] = pTest_own; 

			pTestModule.usePropertyDescrAlias = true;
			pTestModule.idpropertys[(UInt16)pTest_own.aliasID] = pTest_own;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Test), property(own / 18).");

			Property pTest_state = new Property();
			pTest_state.name = "state";
			pTest_state.properUtype = 17;
			pTest_state.properFlags = 4;
			pTest_state.aliasID = 5;
			Int32 Test_state_defval;
			Int32.TryParse("100", out Test_state_defval);
			pTest_state.defaultVal = Test_state_defval;
			pTestModule.propertys["state"] = pTest_state; 

			pTestModule.usePropertyDescrAlias = true;
			pTestModule.idpropertys[(UInt16)pTest_state.aliasID] = pTest_state;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Test), property(state / 17).");

			List<DATATYPE_BASE> pTest_helloCB_args = new List<DATATYPE_BASE>();
			pTest_helloCB_args.Add(EntityDef.id2datatypes[8]);

			Method pTest_helloCB = new Method();
			pTest_helloCB.name = "helloCB";
			pTest_helloCB.methodUtype = 28;
			pTest_helloCB.aliasID = 1;
			pTest_helloCB.args = pTest_helloCB_args;

			pTestModule.methods["helloCB"] = pTest_helloCB; 
			pTestModule.useMethodDescrAlias = true;
			pTestModule.idmethods[(UInt16)pTest_helloCB.aliasID] = pTest_helloCB;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Test), method(helloCB / 28).");

			List<DATATYPE_BASE> pTest_say_args = new List<DATATYPE_BASE>();
			pTest_say_args.Add(EntityDef.id2datatypes[8]);

			Method pTest_say = new Method();
			pTest_say.name = "say";
			pTest_say.methodUtype = 27;
			pTest_say.aliasID = -1;
			pTest_say.args = pTest_say_args;

			pTestModule.methods["say"] = pTest_say; 
			pTestModule.base_methods["say"] = pTest_say;

			pTestModule.idbase_methods[pTest_say.methodUtype] = pTest_say;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Test), method(say / 27).");

			List<DATATYPE_BASE> pTest_hello_args = new List<DATATYPE_BASE>();
			pTest_hello_args.Add(EntityDef.id2datatypes[8]);

			Method pTest_hello = new Method();
			pTest_hello.name = "hello";
			pTest_hello.methodUtype = 26;
			pTest_hello.aliasID = -1;
			pTest_hello.args = pTest_hello_args;

			pTestModule.methods["hello"] = pTest_hello; 
			pTestModule.cell_methods["hello"] = pTest_hello;

			pTestModule.idcell_methods[pTest_hello.methodUtype] = pTest_hello;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Test), method(hello / 26).");

			ScriptModule pTestNoBaseModule = new ScriptModule("TestNoBase");
			EntityDef.moduledefs["TestNoBase"] = pTestNoBaseModule;
			EntityDef.idmoduledefs[4] = pTestNoBaseModule;

			Property pTestNoBase_position = new Property();
			pTestNoBase_position.name = "position";
			pTestNoBase_position.properUtype = 40000;
			pTestNoBase_position.properFlags = 4;
			pTestNoBase_position.aliasID = 1;
			Vector3 TestNoBase_position_defval = new Vector3();
			pTestNoBase_position.defaultVal = TestNoBase_position_defval;
			pTestNoBaseModule.propertys["position"] = pTestNoBase_position; 

			pTestNoBaseModule.usePropertyDescrAlias = true;
			pTestNoBaseModule.idpropertys[(UInt16)pTestNoBase_position.aliasID] = pTestNoBase_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestNoBase), property(position / 40000).");

			Property pTestNoBase_direction = new Property();
			pTestNoBase_direction.name = "direction";
			pTestNoBase_direction.properUtype = 40001;
			pTestNoBase_direction.properFlags = 4;
			pTestNoBase_direction.aliasID = 2;
			Vector3 TestNoBase_direction_defval = new Vector3();
			pTestNoBase_direction.defaultVal = TestNoBase_direction_defval;
			pTestNoBaseModule.propertys["direction"] = pTestNoBase_direction; 

			pTestNoBaseModule.usePropertyDescrAlias = true;
			pTestNoBaseModule.idpropertys[(UInt16)pTestNoBase_direction.aliasID] = pTestNoBase_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestNoBase), property(direction / 40001).");

			Property pTestNoBase_spaceID = new Property();
			pTestNoBase_spaceID.name = "spaceID";
			pTestNoBase_spaceID.properUtype = 40002;
			pTestNoBase_spaceID.properFlags = 16;
			pTestNoBase_spaceID.aliasID = 3;
			UInt32 TestNoBase_spaceID_defval;
			UInt32.TryParse("", out TestNoBase_spaceID_defval);
			pTestNoBase_spaceID.defaultVal = TestNoBase_spaceID_defval;
			pTestNoBaseModule.propertys["spaceID"] = pTestNoBase_spaceID; 

			pTestNoBaseModule.usePropertyDescrAlias = true;
			pTestNoBaseModule.idpropertys[(UInt16)pTestNoBase_spaceID.aliasID] = pTestNoBase_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestNoBase), property(spaceID / 40002).");

			Property pTestNoBase_own = new Property();
			pTestNoBase_own.name = "own";
			pTestNoBase_own.properUtype = 24;
			pTestNoBase_own.properFlags = 8;
			pTestNoBase_own.aliasID = 4;
			Int32 TestNoBase_own_defval;
			Int32.TryParse("1001", out TestNoBase_own_defval);
			pTestNoBase_own.defaultVal = TestNoBase_own_defval;
			pTestNoBaseModule.propertys["own"] = pTestNoBase_own; 

			pTestNoBaseModule.usePropertyDescrAlias = true;
			pTestNoBaseModule.idpropertys[(UInt16)pTestNoBase_own.aliasID] = pTestNoBase_own;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestNoBase), property(own / 24).");

			Property pTestNoBase_state = new Property();
			pTestNoBase_state.name = "state";
			pTestNoBase_state.properUtype = 23;
			pTestNoBase_state.properFlags = 4;
			pTestNoBase_state.aliasID = 5;
			Int32 TestNoBase_state_defval;
			Int32.TryParse("100", out TestNoBase_state_defval);
			pTestNoBase_state.defaultVal = TestNoBase_state_defval;
			pTestNoBaseModule.propertys["state"] = pTestNoBase_state; 

			pTestNoBaseModule.usePropertyDescrAlias = true;
			pTestNoBaseModule.idpropertys[(UInt16)pTestNoBase_state.aliasID] = pTestNoBase_state;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestNoBase), property(state / 23).");

			List<DATATYPE_BASE> pTestNoBase_helloCB_args = new List<DATATYPE_BASE>();
			pTestNoBase_helloCB_args.Add(EntityDef.id2datatypes[8]);

			Method pTestNoBase_helloCB = new Method();
			pTestNoBase_helloCB.name = "helloCB";
			pTestNoBase_helloCB.methodUtype = 30;
			pTestNoBase_helloCB.aliasID = 1;
			pTestNoBase_helloCB.args = pTestNoBase_helloCB_args;

			pTestNoBaseModule.methods["helloCB"] = pTestNoBase_helloCB; 
			pTestNoBaseModule.useMethodDescrAlias = true;
			pTestNoBaseModule.idmethods[(UInt16)pTestNoBase_helloCB.aliasID] = pTestNoBase_helloCB;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestNoBase), method(helloCB / 30).");

			List<DATATYPE_BASE> pTestNoBase_hello_args = new List<DATATYPE_BASE>();
			pTestNoBase_hello_args.Add(EntityDef.id2datatypes[8]);

			Method pTestNoBase_hello = new Method();
			pTestNoBase_hello.name = "hello";
			pTestNoBase_hello.methodUtype = 29;
			pTestNoBase_hello.aliasID = -1;
			pTestNoBase_hello.args = pTestNoBase_hello_args;

			pTestNoBaseModule.methods["hello"] = pTestNoBase_hello; 
			pTestNoBaseModule.cell_methods["hello"] = pTestNoBase_hello;

			pTestNoBaseModule.idcell_methods[pTestNoBase_hello.methodUtype] = pTestNoBase_hello;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(TestNoBase), method(hello / 29).");

			ScriptModule pMonsterModule = new ScriptModule("Monster");
			EntityDef.moduledefs["Monster"] = pMonsterModule;
			EntityDef.idmoduledefs[5] = pMonsterModule;

			Property pMonster_position = new Property();
			pMonster_position.name = "position";
			pMonster_position.properUtype = 40000;
			pMonster_position.properFlags = 4;
			pMonster_position.aliasID = 1;
			Vector3 Monster_position_defval = new Vector3();
			pMonster_position.defaultVal = Monster_position_defval;
			pMonsterModule.propertys["position"] = pMonster_position; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_position.aliasID] = pMonster_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(position / 40000).");

			Property pMonster_direction = new Property();
			pMonster_direction.name = "direction";
			pMonster_direction.properUtype = 40001;
			pMonster_direction.properFlags = 4;
			pMonster_direction.aliasID = 2;
			Vector3 Monster_direction_defval = new Vector3();
			pMonster_direction.defaultVal = Monster_direction_defval;
			pMonsterModule.propertys["direction"] = pMonster_direction; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_direction.aliasID] = pMonster_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(direction / 40001).");

			Property pMonster_spaceID = new Property();
			pMonster_spaceID.name = "spaceID";
			pMonster_spaceID.properUtype = 40002;
			pMonster_spaceID.properFlags = 16;
			pMonster_spaceID.aliasID = 3;
			UInt32 Monster_spaceID_defval;
			UInt32.TryParse("", out Monster_spaceID_defval);
			pMonster_spaceID.defaultVal = Monster_spaceID_defval;
			pMonsterModule.propertys["spaceID"] = pMonster_spaceID; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_spaceID.aliasID] = pMonster_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(spaceID / 40002).");

			Property pMonster_HP = new Property();
			pMonster_HP.name = "HP";
			pMonster_HP.properUtype = 47001;
			pMonster_HP.properFlags = 4;
			pMonster_HP.aliasID = 4;
			Int32 Monster_HP_defval;
			Int32.TryParse("0", out Monster_HP_defval);
			pMonster_HP.defaultVal = Monster_HP_defval;
			pMonsterModule.propertys["HP"] = pMonster_HP; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_HP.aliasID] = pMonster_HP;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(HP / 47001).");

			Property pMonster_HP_Max = new Property();
			pMonster_HP_Max.name = "HP_Max";
			pMonster_HP_Max.properUtype = 47002;
			pMonster_HP_Max.properFlags = 4;
			pMonster_HP_Max.aliasID = 5;
			Int32 Monster_HP_Max_defval;
			Int32.TryParse("0", out Monster_HP_Max_defval);
			pMonster_HP_Max.defaultVal = Monster_HP_Max_defval;
			pMonsterModule.propertys["HP_Max"] = pMonster_HP_Max; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_HP_Max.aliasID] = pMonster_HP_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(HP_Max / 47002).");

			Property pMonster_MP = new Property();
			pMonster_MP.name = "MP";
			pMonster_MP.properUtype = 47003;
			pMonster_MP.properFlags = 4;
			pMonster_MP.aliasID = 6;
			Int32 Monster_MP_defval;
			Int32.TryParse("0", out Monster_MP_defval);
			pMonster_MP.defaultVal = Monster_MP_defval;
			pMonsterModule.propertys["MP"] = pMonster_MP; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_MP.aliasID] = pMonster_MP;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(MP / 47003).");

			Property pMonster_MP_Max = new Property();
			pMonster_MP_Max.name = "MP_Max";
			pMonster_MP_Max.properUtype = 47004;
			pMonster_MP_Max.properFlags = 4;
			pMonster_MP_Max.aliasID = 7;
			Int32 Monster_MP_Max_defval;
			Int32.TryParse("0", out Monster_MP_Max_defval);
			pMonster_MP_Max.defaultVal = Monster_MP_Max_defval;
			pMonsterModule.propertys["MP_Max"] = pMonster_MP_Max; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_MP_Max.aliasID] = pMonster_MP_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(MP_Max / 47004).");

			Property pMonster_entityNO = new Property();
			pMonster_entityNO.name = "entityNO";
			pMonster_entityNO.properUtype = 51007;
			pMonster_entityNO.properFlags = 4;
			pMonster_entityNO.aliasID = 8;
			UInt32 Monster_entityNO_defval;
			UInt32.TryParse("0", out Monster_entityNO_defval);
			pMonster_entityNO.defaultVal = Monster_entityNO_defval;
			pMonsterModule.propertys["entityNO"] = pMonster_entityNO; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_entityNO.aliasID] = pMonster_entityNO;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(entityNO / 51007).");

			Property pMonster_forbids = new Property();
			pMonster_forbids.name = "forbids";
			pMonster_forbids.properUtype = 47005;
			pMonster_forbids.properFlags = 4;
			pMonster_forbids.aliasID = 9;
			Int32 Monster_forbids_defval;
			Int32.TryParse("0", out Monster_forbids_defval);
			pMonster_forbids.defaultVal = Monster_forbids_defval;
			pMonsterModule.propertys["forbids"] = pMonster_forbids; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_forbids.aliasID] = pMonster_forbids;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(forbids / 47005).");

			Property pMonster_modelID = new Property();
			pMonster_modelID.name = "modelID";
			pMonster_modelID.properUtype = 41006;
			pMonster_modelID.properFlags = 4;
			pMonster_modelID.aliasID = 10;
			UInt32 Monster_modelID_defval;
			UInt32.TryParse("0", out Monster_modelID_defval);
			pMonster_modelID.defaultVal = Monster_modelID_defval;
			pMonsterModule.propertys["modelID"] = pMonster_modelID; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_modelID.aliasID] = pMonster_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(modelID / 41006).");

			Property pMonster_modelScale = new Property();
			pMonster_modelScale.name = "modelScale";
			pMonster_modelScale.properUtype = 41007;
			pMonster_modelScale.properFlags = 4;
			pMonster_modelScale.aliasID = 11;
			Byte Monster_modelScale_defval;
			Byte.TryParse("30", out Monster_modelScale_defval);
			pMonster_modelScale.defaultVal = Monster_modelScale_defval;
			pMonsterModule.propertys["modelScale"] = pMonster_modelScale; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_modelScale.aliasID] = pMonster_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(modelScale / 41007).");

			Property pMonster_moveSpeed = new Property();
			pMonster_moveSpeed.name = "moveSpeed";
			pMonster_moveSpeed.properUtype = 32;
			pMonster_moveSpeed.properFlags = 4;
			pMonster_moveSpeed.aliasID = 12;
			Byte Monster_moveSpeed_defval;
			Byte.TryParse("50", out Monster_moveSpeed_defval);
			pMonster_moveSpeed.defaultVal = Monster_moveSpeed_defval;
			pMonsterModule.propertys["moveSpeed"] = pMonster_moveSpeed; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_moveSpeed.aliasID] = pMonster_moveSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(moveSpeed / 32).");

			Property pMonster_name = new Property();
			pMonster_name.name = "name";
			pMonster_name.properUtype = 41003;
			pMonster_name.properFlags = 4;
			pMonster_name.aliasID = 13;
			string Monster_name_defval = "";
			pMonster_name.defaultVal = Monster_name_defval;
			pMonsterModule.propertys["name"] = pMonster_name; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_name.aliasID] = pMonster_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(name / 41003).");

			Property pMonster_state = new Property();
			pMonster_state.name = "state";
			pMonster_state.properUtype = 47006;
			pMonster_state.properFlags = 4;
			pMonster_state.aliasID = 14;
			SByte Monster_state_defval;
			SByte.TryParse("0", out Monster_state_defval);
			pMonster_state.defaultVal = Monster_state_defval;
			pMonsterModule.propertys["state"] = pMonster_state; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_state.aliasID] = pMonster_state;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(state / 47006).");

			Property pMonster_subState = new Property();
			pMonster_subState.name = "subState";
			pMonster_subState.properUtype = 47007;
			pMonster_subState.properFlags = 4;
			pMonster_subState.aliasID = 15;
			Byte Monster_subState_defval;
			Byte.TryParse("", out Monster_subState_defval);
			pMonster_subState.defaultVal = Monster_subState_defval;
			pMonsterModule.propertys["subState"] = pMonster_subState; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_subState.aliasID] = pMonster_subState;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(subState / 47007).");

			Property pMonster_uid = new Property();
			pMonster_uid.name = "uid";
			pMonster_uid.properUtype = 41004;
			pMonster_uid.properFlags = 4;
			pMonster_uid.aliasID = 16;
			UInt32 Monster_uid_defval;
			UInt32.TryParse("0", out Monster_uid_defval);
			pMonster_uid.defaultVal = Monster_uid_defval;
			pMonsterModule.propertys["uid"] = pMonster_uid; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_uid.aliasID] = pMonster_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(uid / 41004).");

			Property pMonster_utype = new Property();
			pMonster_utype.name = "utype";
			pMonster_utype.properUtype = 41005;
			pMonster_utype.properFlags = 4;
			pMonster_utype.aliasID = 17;
			UInt32 Monster_utype_defval;
			UInt32.TryParse("0", out Monster_utype_defval);
			pMonster_utype.defaultVal = Monster_utype_defval;
			pMonsterModule.propertys["utype"] = pMonster_utype; 

			pMonsterModule.usePropertyDescrAlias = true;
			pMonsterModule.idpropertys[(UInt16)pMonster_utype.aliasID] = pMonster_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), property(utype / 41005).");

			List<DATATYPE_BASE> pMonster_recvDamage_args = new List<DATATYPE_BASE>();
			pMonster_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pMonster_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pMonster_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pMonster_recvDamage_args.Add(EntityDef.id2datatypes[8]);

			Method pMonster_recvDamage = new Method();
			pMonster_recvDamage.name = "recvDamage";
			pMonster_recvDamage.methodUtype = 34;
			pMonster_recvDamage.aliasID = 1;
			pMonster_recvDamage.args = pMonster_recvDamage_args;

			pMonsterModule.methods["recvDamage"] = pMonster_recvDamage; 
			pMonsterModule.useMethodDescrAlias = true;
			pMonsterModule.idmethods[(UInt16)pMonster_recvDamage.aliasID] = pMonster_recvDamage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Monster), method(recvDamage / 34).");

			ScriptModule pNPCModule = new ScriptModule("NPC");
			EntityDef.moduledefs["NPC"] = pNPCModule;
			EntityDef.idmoduledefs[6] = pNPCModule;

			Property pNPC_position = new Property();
			pNPC_position.name = "position";
			pNPC_position.properUtype = 40000;
			pNPC_position.properFlags = 4;
			pNPC_position.aliasID = 1;
			Vector3 NPC_position_defval = new Vector3();
			pNPC_position.defaultVal = NPC_position_defval;
			pNPCModule.propertys["position"] = pNPC_position; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_position.aliasID] = pNPC_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(position / 40000).");

			Property pNPC_direction = new Property();
			pNPC_direction.name = "direction";
			pNPC_direction.properUtype = 40001;
			pNPC_direction.properFlags = 4;
			pNPC_direction.aliasID = 2;
			Vector3 NPC_direction_defval = new Vector3();
			pNPC_direction.defaultVal = NPC_direction_defval;
			pNPCModule.propertys["direction"] = pNPC_direction; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_direction.aliasID] = pNPC_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(direction / 40001).");

			Property pNPC_spaceID = new Property();
			pNPC_spaceID.name = "spaceID";
			pNPC_spaceID.properUtype = 40002;
			pNPC_spaceID.properFlags = 16;
			pNPC_spaceID.aliasID = 3;
			UInt32 NPC_spaceID_defval;
			UInt32.TryParse("", out NPC_spaceID_defval);
			pNPC_spaceID.defaultVal = NPC_spaceID_defval;
			pNPCModule.propertys["spaceID"] = pNPC_spaceID; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_spaceID.aliasID] = pNPC_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(spaceID / 40002).");

			Property pNPC_entityNO = new Property();
			pNPC_entityNO.name = "entityNO";
			pNPC_entityNO.properUtype = 51007;
			pNPC_entityNO.properFlags = 4;
			pNPC_entityNO.aliasID = 4;
			UInt32 NPC_entityNO_defval;
			UInt32.TryParse("0", out NPC_entityNO_defval);
			pNPC_entityNO.defaultVal = NPC_entityNO_defval;
			pNPCModule.propertys["entityNO"] = pNPC_entityNO; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_entityNO.aliasID] = pNPC_entityNO;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(entityNO / 51007).");

			Property pNPC_modelID = new Property();
			pNPC_modelID.name = "modelID";
			pNPC_modelID.properUtype = 41006;
			pNPC_modelID.properFlags = 4;
			pNPC_modelID.aliasID = 5;
			UInt32 NPC_modelID_defval;
			UInt32.TryParse("0", out NPC_modelID_defval);
			pNPC_modelID.defaultVal = NPC_modelID_defval;
			pNPCModule.propertys["modelID"] = pNPC_modelID; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_modelID.aliasID] = pNPC_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(modelID / 41006).");

			Property pNPC_modelScale = new Property();
			pNPC_modelScale.name = "modelScale";
			pNPC_modelScale.properUtype = 41007;
			pNPC_modelScale.properFlags = 4;
			pNPC_modelScale.aliasID = 6;
			Byte NPC_modelScale_defval;
			Byte.TryParse("30", out NPC_modelScale_defval);
			pNPC_modelScale.defaultVal = NPC_modelScale_defval;
			pNPCModule.propertys["modelScale"] = pNPC_modelScale; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_modelScale.aliasID] = pNPC_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(modelScale / 41007).");

			Property pNPC_moveSpeed = new Property();
			pNPC_moveSpeed.name = "moveSpeed";
			pNPC_moveSpeed.properUtype = 43;
			pNPC_moveSpeed.properFlags = 4;
			pNPC_moveSpeed.aliasID = 7;
			Byte NPC_moveSpeed_defval;
			Byte.TryParse("50", out NPC_moveSpeed_defval);
			pNPC_moveSpeed.defaultVal = NPC_moveSpeed_defval;
			pNPCModule.propertys["moveSpeed"] = pNPC_moveSpeed; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_moveSpeed.aliasID] = pNPC_moveSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(moveSpeed / 43).");

			Property pNPC_name = new Property();
			pNPC_name.name = "name";
			pNPC_name.properUtype = 41003;
			pNPC_name.properFlags = 4;
			pNPC_name.aliasID = 8;
			string NPC_name_defval = "";
			pNPC_name.defaultVal = NPC_name_defval;
			pNPCModule.propertys["name"] = pNPC_name; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_name.aliasID] = pNPC_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(name / 41003).");

			Property pNPC_uid = new Property();
			pNPC_uid.name = "uid";
			pNPC_uid.properUtype = 41004;
			pNPC_uid.properFlags = 4;
			pNPC_uid.aliasID = 9;
			UInt32 NPC_uid_defval;
			UInt32.TryParse("0", out NPC_uid_defval);
			pNPC_uid.defaultVal = NPC_uid_defval;
			pNPCModule.propertys["uid"] = pNPC_uid; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_uid.aliasID] = pNPC_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(uid / 41004).");

			Property pNPC_utype = new Property();
			pNPC_utype.name = "utype";
			pNPC_utype.properUtype = 41005;
			pNPC_utype.properFlags = 4;
			pNPC_utype.aliasID = 10;
			UInt32 NPC_utype_defval;
			UInt32.TryParse("0", out NPC_utype_defval);
			pNPC_utype.defaultVal = NPC_utype_defval;
			pNPCModule.propertys["utype"] = pNPC_utype; 

			pNPCModule.usePropertyDescrAlias = true;
			pNPCModule.idpropertys[(UInt16)pNPC_utype.aliasID] = pNPC_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(NPC), property(utype / 41005).");

			pNPCModule.useMethodDescrAlias = true;
			ScriptModule pGateModule = new ScriptModule("Gate");
			EntityDef.moduledefs["Gate"] = pGateModule;
			EntityDef.idmoduledefs[7] = pGateModule;

			Property pGate_position = new Property();
			pGate_position.name = "position";
			pGate_position.properUtype = 40000;
			pGate_position.properFlags = 4;
			pGate_position.aliasID = 1;
			Vector3 Gate_position_defval = new Vector3();
			pGate_position.defaultVal = Gate_position_defval;
			pGateModule.propertys["position"] = pGate_position; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_position.aliasID] = pGate_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(position / 40000).");

			Property pGate_direction = new Property();
			pGate_direction.name = "direction";
			pGate_direction.properUtype = 40001;
			pGate_direction.properFlags = 4;
			pGate_direction.aliasID = 2;
			Vector3 Gate_direction_defval = new Vector3();
			pGate_direction.defaultVal = Gate_direction_defval;
			pGateModule.propertys["direction"] = pGate_direction; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_direction.aliasID] = pGate_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(direction / 40001).");

			Property pGate_spaceID = new Property();
			pGate_spaceID.name = "spaceID";
			pGate_spaceID.properUtype = 40002;
			pGate_spaceID.properFlags = 16;
			pGate_spaceID.aliasID = 3;
			UInt32 Gate_spaceID_defval;
			UInt32.TryParse("", out Gate_spaceID_defval);
			pGate_spaceID.defaultVal = Gate_spaceID_defval;
			pGateModule.propertys["spaceID"] = pGate_spaceID; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_spaceID.aliasID] = pGate_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(spaceID / 40002).");

			Property pGate_entityNO = new Property();
			pGate_entityNO.name = "entityNO";
			pGate_entityNO.properUtype = 51007;
			pGate_entityNO.properFlags = 4;
			pGate_entityNO.aliasID = 4;
			UInt32 Gate_entityNO_defval;
			UInt32.TryParse("0", out Gate_entityNO_defval);
			pGate_entityNO.defaultVal = Gate_entityNO_defval;
			pGateModule.propertys["entityNO"] = pGate_entityNO; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_entityNO.aliasID] = pGate_entityNO;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(entityNO / 51007).");

			Property pGate_modelID = new Property();
			pGate_modelID.name = "modelID";
			pGate_modelID.properUtype = 41006;
			pGate_modelID.properFlags = 4;
			pGate_modelID.aliasID = 5;
			UInt32 Gate_modelID_defval;
			UInt32.TryParse("0", out Gate_modelID_defval);
			pGate_modelID.defaultVal = Gate_modelID_defval;
			pGateModule.propertys["modelID"] = pGate_modelID; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_modelID.aliasID] = pGate_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(modelID / 41006).");

			Property pGate_modelScale = new Property();
			pGate_modelScale.name = "modelScale";
			pGate_modelScale.properUtype = 41007;
			pGate_modelScale.properFlags = 4;
			pGate_modelScale.aliasID = 6;
			Byte Gate_modelScale_defval;
			Byte.TryParse("30", out Gate_modelScale_defval);
			pGate_modelScale.defaultVal = Gate_modelScale_defval;
			pGateModule.propertys["modelScale"] = pGate_modelScale; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_modelScale.aliasID] = pGate_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(modelScale / 41007).");

			Property pGate_name = new Property();
			pGate_name.name = "name";
			pGate_name.properUtype = 41003;
			pGate_name.properFlags = 4;
			pGate_name.aliasID = 7;
			string Gate_name_defval = "";
			pGate_name.defaultVal = Gate_name_defval;
			pGateModule.propertys["name"] = pGate_name; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_name.aliasID] = pGate_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(name / 41003).");

			Property pGate_uid = new Property();
			pGate_uid.name = "uid";
			pGate_uid.properUtype = 41004;
			pGate_uid.properFlags = 4;
			pGate_uid.aliasID = 8;
			UInt32 Gate_uid_defval;
			UInt32.TryParse("0", out Gate_uid_defval);
			pGate_uid.defaultVal = Gate_uid_defval;
			pGateModule.propertys["uid"] = pGate_uid; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_uid.aliasID] = pGate_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(uid / 41004).");

			Property pGate_utype = new Property();
			pGate_utype.name = "utype";
			pGate_utype.properUtype = 41005;
			pGate_utype.properFlags = 4;
			pGate_utype.aliasID = 9;
			UInt32 Gate_utype_defval;
			UInt32.TryParse("0", out Gate_utype_defval);
			pGate_utype.defaultVal = Gate_utype_defval;
			pGateModule.propertys["utype"] = pGate_utype; 

			pGateModule.usePropertyDescrAlias = true;
			pGateModule.idpropertys[(UInt16)pGate_utype.aliasID] = pGate_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Gate), property(utype / 41005).");

			pGateModule.useMethodDescrAlias = true;
		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "ENTITY_SUBSTATE";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "UID";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "ENTITY_UTYPE";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "ENTITY_STATE";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "ENTITY_FORBIDS";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "UID1";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "DIRECTION3D";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "ENTITY_FORBID_COUNTER";
				DATATYPE_ENTITY_FORBID_COUNTER datatype = new DATATYPE_ENTITY_FORBID_COUNTER();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "ENTITYID_LIST";
				DATATYPE_ENTITYID_LIST datatype = new DATATYPE_ENTITYID_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "AVATAR_DATA";
				DATATYPE_AVATAR_DATA datatype = new DATATYPE_AVATAR_DATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 25;
				string typeName = "AVATAR_INFOS";
				DATATYPE_AVATAR_INFOS datatype = new DATATYPE_AVATAR_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 26;
				string typeName = "AVATAR_INFOS_LIST";
				DATATYPE_AVATAR_INFOS_LIST datatype = new DATATYPE_AVATAR_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 28;
				string typeName = "BAG";
				DATATYPE_BAG datatype = new DATATYPE_BAG();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 31;
				string typeName = "EXAMPLES";
				DATATYPE_EXAMPLES datatype = new DATATYPE_EXAMPLES();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 32;
				string typeName = "AnonymousArray_32";
				DATATYPE_AnonymousArray_32 datatype = new DATATYPE_AnonymousArray_32();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 33;
				string typeName = "AnonymousArray_33";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 34;
				string typeName = "AnonymousArray_34";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 35;
				string typeName = "AnonymousArray_35";
				string name = "ENTITY_COMPONENT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}