/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	using MessageID = System.UInt16;

	// engine-c++ messages

	public class Message
	{
		public MessageID id = 0;
		public string name;
		public Int16 msglen = -1;
		public List<Byte> argtypes = null;
		public sbyte argsType = 0;

		public Message(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes)
		{
			id = msgid;
			name = msgname;
			msglen = length;
			argsType = argstype;

			argtypes = msgargtypes;
			// Dbg.DEBUG_MSG(string.Format("Message::Message() : ({ 0 } / {1} / {2})!", 
			//		msgname, msgid, msglen));
		}

		public virtual void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Client_onReloginBaseappFailed : Message
	{

		public Message_Client_onReloginBaseappFailed(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			UInt16 arg1 = msgstream.readUint16();
			KBEngineApp.app.Client_onReloginBaseappFailed(arg1);
		}
	}

	public class Message_Client_onEntityLeaveWorldOptimized : Message
	{

		public Message_Client_onEntityLeaveWorldOptimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onEntityLeaveWorldOptimized(msgstream);
		}
	}

	public class Message_Client_onRemoteMethodCallOptimized : Message
	{

		public Message_Client_onRemoteMethodCallOptimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onRemoteMethodCallOptimized(msgstream);
		}
	}

	public class Message_Client_onUpdatePropertysOptimized : Message
	{

		public Message_Client_onUpdatePropertysOptimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdatePropertysOptimized(msgstream);
		}
	}

	public class Message_Client_onSetEntityPosAndDir : Message
	{

		public Message_Client_onSetEntityPosAndDir(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onSetEntityPosAndDir(msgstream);
		}
	}

	public class Message_Client_onUpdateBasePos : Message
	{

		public Message_Client_onUpdateBasePos(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			float arg1 = msgstream.readFloat();
			float arg2 = msgstream.readFloat();
			float arg3 = msgstream.readFloat();
			KBEngineApp.app.Client_onUpdateBasePos(arg1, arg2, arg3);
		}
	}

	public class Message_Client_onUpdateBaseDir : Message
	{

		public Message_Client_onUpdateBaseDir(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateBaseDir(msgstream);
		}
	}

	public class Message_Client_onUpdateBasePosXZ : Message
	{

		public Message_Client_onUpdateBasePosXZ(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			float arg1 = msgstream.readFloat();
			float arg2 = msgstream.readFloat();
			KBEngineApp.app.Client_onUpdateBasePosXZ(arg1, arg2);
		}
	}

	public class Message_Client_onUpdateData : Message
	{

		public Message_Client_onUpdateData(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData(msgstream);
		}
	}

	public class Message_Client_onUpdateData_ypr : Message
	{

		public Message_Client_onUpdateData_ypr(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_ypr(msgstream);
		}
	}

	public class Message_Client_onUpdateData_yp : Message
	{

		public Message_Client_onUpdateData_yp(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_yp(msgstream);
		}
	}

	public class Message_Client_onUpdateData_yr : Message
	{

		public Message_Client_onUpdateData_yr(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_yr(msgstream);
		}
	}

	public class Message_Client_onUpdateData_pr : Message
	{

		public Message_Client_onUpdateData_pr(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_pr(msgstream);
		}
	}

	public class Message_Client_onUpdateData_y : Message
	{

		public Message_Client_onUpdateData_y(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_y(msgstream);
		}
	}

	public class Message_Client_onUpdateData_p : Message
	{

		public Message_Client_onUpdateData_p(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_p(msgstream);
		}
	}

	public class Message_Client_onUpdateData_r : Message
	{

		public Message_Client_onUpdateData_r(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_r(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz : Message
	{

		public Message_Client_onUpdateData_xz(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_ypr : Message
	{

		public Message_Client_onUpdateData_xz_ypr(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_ypr(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_yp : Message
	{

		public Message_Client_onUpdateData_xz_yp(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_yp(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_yr : Message
	{

		public Message_Client_onUpdateData_xz_yr(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_yr(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_pr : Message
	{

		public Message_Client_onUpdateData_xz_pr(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_pr(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_y : Message
	{

		public Message_Client_onUpdateData_xz_y(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_y(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_p : Message
	{

		public Message_Client_onUpdateData_xz_p(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_p(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_r : Message
	{

		public Message_Client_onUpdateData_xz_r(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_r(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz : Message
	{

		public Message_Client_onUpdateData_xyz(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_ypr : Message
	{

		public Message_Client_onUpdateData_xyz_ypr(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_ypr(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_yp : Message
	{

		public Message_Client_onUpdateData_xyz_yp(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_yp(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_yr : Message
	{

		public Message_Client_onUpdateData_xyz_yr(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_yr(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_pr : Message
	{

		public Message_Client_onUpdateData_xyz_pr(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_pr(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_y : Message
	{

		public Message_Client_onUpdateData_xyz_y(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_y(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_p : Message
	{

		public Message_Client_onUpdateData_xyz_p(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_p(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_r : Message
	{

		public Message_Client_onUpdateData_xyz_r(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_r(msgstream);
		}
	}

	public class Message_Client_onUpdateData_ypr_optimized : Message
	{

		public Message_Client_onUpdateData_ypr_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_ypr_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_yp_optimized : Message
	{

		public Message_Client_onUpdateData_yp_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_yp_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_yr_optimized : Message
	{

		public Message_Client_onUpdateData_yr_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_yr_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_pr_optimized : Message
	{

		public Message_Client_onUpdateData_pr_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_pr_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_y_optimized : Message
	{

		public Message_Client_onUpdateData_y_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_y_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_p_optimized : Message
	{

		public Message_Client_onUpdateData_p_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_p_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_r_optimized : Message
	{

		public Message_Client_onUpdateData_r_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_r_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_optimized : Message
	{

		public Message_Client_onUpdateData_xz_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_ypr_optimized : Message
	{

		public Message_Client_onUpdateData_xz_ypr_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_ypr_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_yp_optimized : Message
	{

		public Message_Client_onUpdateData_xz_yp_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_yp_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_yr_optimized : Message
	{

		public Message_Client_onUpdateData_xz_yr_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_yr_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_pr_optimized : Message
	{

		public Message_Client_onUpdateData_xz_pr_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_pr_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_y_optimized : Message
	{

		public Message_Client_onUpdateData_xz_y_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_y_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_p_optimized : Message
	{

		public Message_Client_onUpdateData_xz_p_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_p_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xz_r_optimized : Message
	{

		public Message_Client_onUpdateData_xz_r_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xz_r_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_optimized : Message
	{

		public Message_Client_onUpdateData_xyz_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_ypr_optimized : Message
	{

		public Message_Client_onUpdateData_xyz_ypr_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_ypr_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_yp_optimized : Message
	{

		public Message_Client_onUpdateData_xyz_yp_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_yp_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_yr_optimized : Message
	{

		public Message_Client_onUpdateData_xyz_yr_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_yr_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_pr_optimized : Message
	{

		public Message_Client_onUpdateData_xyz_pr_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_pr_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_y_optimized : Message
	{

		public Message_Client_onUpdateData_xyz_y_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_y_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_p_optimized : Message
	{

		public Message_Client_onUpdateData_xyz_p_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_p_optimized(msgstream);
		}
	}

	public class Message_Client_onUpdateData_xyz_r_optimized : Message
	{

		public Message_Client_onUpdateData_xyz_r_optimized(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdateData_xyz_r_optimized(msgstream);
		}
	}

	public class Message_Client_onImportServerErrorsDescr : Message
	{

		public Message_Client_onImportServerErrorsDescr(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onImportServerErrorsDescr(msgstream);
		}
	}

	public class Message_Client_onImportClientSDK : Message
	{

		public Message_Client_onImportClientSDK(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onImportClientSDK(msgstream);
		}
	}

	public class Message_Client_initSpaceData : Message
	{

		public Message_Client_initSpaceData(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_initSpaceData(msgstream);
		}
	}

	public class Message_Client_setSpaceData : Message
	{

		public Message_Client_setSpaceData(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			UInt32 arg1 = msgstream.readUint32();
			string arg2 = msgstream.readString();
			string arg3 = msgstream.readString();
			KBEngineApp.app.Client_setSpaceData(arg1, arg2, arg3);
		}
	}

	public class Message_Client_delSpaceData : Message
	{

		public Message_Client_delSpaceData(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			UInt32 arg1 = msgstream.readUint32();
			string arg2 = msgstream.readString();
			KBEngineApp.app.Client_delSpaceData(arg1, arg2);
		}
	}

	public class Message_Client_onReqAccountResetPasswordCB : Message
	{

		public Message_Client_onReqAccountResetPasswordCB(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			UInt16 arg1 = msgstream.readUint16();
			KBEngineApp.app.Client_onReqAccountResetPasswordCB(arg1);
		}
	}

	public class Message_Client_onReqAccountBindEmailCB : Message
	{

		public Message_Client_onReqAccountBindEmailCB(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			UInt16 arg1 = msgstream.readUint16();
			KBEngineApp.app.Client_onReqAccountBindEmailCB(arg1);
		}
	}

	public class Message_Client_onReqAccountNewPasswordCB : Message
	{

		public Message_Client_onReqAccountNewPasswordCB(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			UInt16 arg1 = msgstream.readUint16();
			KBEngineApp.app.Client_onReqAccountNewPasswordCB(arg1);
		}
	}

	public class Message_Client_onReloginBaseappSuccessfully : Message
	{

		public Message_Client_onReloginBaseappSuccessfully(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onReloginBaseappSuccessfully(msgstream);
		}
	}

	public class Message_Client_onAppActiveTickCB : Message
	{

		public Message_Client_onAppActiveTickCB(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onAppActiveTickCB();
		}
	}

	public class Message_Client_onCreateAccountResult : Message
	{

		public Message_Client_onCreateAccountResult(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onCreateAccountResult(msgstream);
		}
	}

	public class Message_Client_onLoginSuccessfully : Message
	{

		public Message_Client_onLoginSuccessfully(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onLoginSuccessfully(msgstream);
		}
	}

	public class Message_Client_onLoginFailed : Message
	{

		public Message_Client_onLoginFailed(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onLoginFailed(msgstream);
		}
	}

	public class Message_Client_onCreatedProxies : Message
	{

		public Message_Client_onCreatedProxies(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			UInt64 arg1 = msgstream.readUint64();
			Int32 arg2 = msgstream.readInt32();
			string arg3 = msgstream.readString();
			KBEngineApp.app.Client_onCreatedProxies(arg1, arg2, arg3);
		}
	}

	public class Message_Client_onLoginBaseappFailed : Message
	{

		public Message_Client_onLoginBaseappFailed(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			UInt16 arg1 = msgstream.readUint16();
			KBEngineApp.app.Client_onLoginBaseappFailed(arg1);
		}
	}

	public class Message_Client_onRemoteMethodCall : Message
	{

		public Message_Client_onRemoteMethodCall(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onRemoteMethodCall(msgstream);
		}
	}

	public class Message_Client_onEntityEnterWorld : Message
	{

		public Message_Client_onEntityEnterWorld(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onEntityEnterWorld(msgstream);
		}
	}

	public class Message_Client_onEntityLeaveWorld : Message
	{

		public Message_Client_onEntityLeaveWorld(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			Int32 arg1 = msgstream.readInt32();
			KBEngineApp.app.Client_onEntityLeaveWorld(arg1);
		}
	}

	public class Message_Client_onEntityEnterSpace : Message
	{

		public Message_Client_onEntityEnterSpace(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onEntityEnterSpace(msgstream);
		}
	}

	public class Message_Client_onEntityLeaveSpace : Message
	{

		public Message_Client_onEntityLeaveSpace(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			Int32 arg1 = msgstream.readInt32();
			KBEngineApp.app.Client_onEntityLeaveSpace(arg1);
		}
	}

	public class Message_Client_onUpdatePropertys : Message
	{

		public Message_Client_onUpdatePropertys(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onUpdatePropertys(msgstream);
		}
	}

	public class Message_Client_onEntityDestroyed : Message
	{

		public Message_Client_onEntityDestroyed(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			Int32 arg1 = msgstream.readInt32();
			KBEngineApp.app.Client_onEntityDestroyed(arg1);
		}
	}

	public class Message_Client_onStreamDataStarted : Message
	{

		public Message_Client_onStreamDataStarted(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			Int16 arg1 = msgstream.readInt16();
			UInt32 arg2 = msgstream.readUint32();
			string arg3 = msgstream.readString();
			KBEngineApp.app.Client_onStreamDataStarted(arg1, arg2, arg3);
		}
	}

	public class Message_Client_onStreamDataRecv : Message
	{

		public Message_Client_onStreamDataRecv(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onStreamDataRecv(msgstream);
		}
	}

	public class Message_Client_onStreamDataCompleted : Message
	{

		public Message_Client_onStreamDataCompleted(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			Int16 arg1 = msgstream.readInt16();
			KBEngineApp.app.Client_onStreamDataCompleted(arg1);
		}
	}

	public class Message_Client_onKicked : Message
	{

		public Message_Client_onKicked(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			UInt16 arg1 = msgstream.readUint16();
			KBEngineApp.app.Client_onKicked(arg1);
		}
	}

	public class Message_Client_onImportClientMessages : Message
	{

		public Message_Client_onImportClientMessages(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onImportClientMessages(msgstream);
		}
	}

	public class Message_Client_onImportClientEntityDef : Message
	{

		public Message_Client_onImportClientEntityDef(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onImportClientEntityDef(msgstream);
		}
	}

	public class Message_Client_onHelloCB : Message
	{

		public Message_Client_onHelloCB(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onHelloCB(msgstream);
		}
	}

	public class Message_Client_onScriptVersionNotMatch : Message
	{

		public Message_Client_onScriptVersionNotMatch(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onScriptVersionNotMatch(msgstream);
		}
	}

	public class Message_Client_onVersionNotMatch : Message
	{

		public Message_Client_onVersionNotMatch(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			KBEngineApp.app.Client_onVersionNotMatch(msgstream);
		}
	}

	public class Message_Client_onControlEntity : Message
	{

		public Message_Client_onControlEntity(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
			Int32 arg1 = msgstream.readInt32();
			SByte arg2 = msgstream.readInt8();
			KBEngineApp.app.Client_onControlEntity(arg1, arg2);
		}
	}

	public class Message_Loginapp_reqCreateAccount : Message
	{

		public Message_Loginapp_reqCreateAccount(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Loginapp_login : Message
	{

		public Message_Loginapp_login(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Loginapp_hello : Message
	{

		public Message_Loginapp_hello(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Loginapp_importClientMessages : Message
	{

		public Message_Loginapp_importClientMessages(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Loginapp_reqCreateMailAccount : Message
	{

		public Message_Loginapp_reqCreateMailAccount(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Loginapp_importClientSDK : Message
	{

		public Message_Loginapp_importClientSDK(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Loginapp_importServerErrorsDescr : Message
	{

		public Message_Loginapp_importServerErrorsDescr(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Loginapp_onClientActiveTick : Message
	{

		public Message_Loginapp_onClientActiveTick(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Loginapp_reqAccountResetPassword : Message
	{

		public Message_Loginapp_reqAccountResetPassword(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_logoutBaseapp : Message
	{

		public Message_Baseapp_logoutBaseapp(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_onUpdateDataFromClient : Message
	{

		public Message_Baseapp_onUpdateDataFromClient(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_onUpdateDataFromClientForControlledEntity : Message
	{

		public Message_Baseapp_onUpdateDataFromClientForControlledEntity(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_reqAccountBindEmail : Message
	{

		public Message_Baseapp_reqAccountBindEmail(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_reqAccountNewPassword : Message
	{

		public Message_Baseapp_reqAccountNewPassword(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Entity_forwardEntityMessageToCellappFromClient : Message
	{

		public Message_Entity_forwardEntityMessageToCellappFromClient(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_hello : Message
	{

		public Message_Baseapp_hello(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_loginBaseapp : Message
	{

		public Message_Baseapp_loginBaseapp(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_reloginBaseapp : Message
	{

		public Message_Baseapp_reloginBaseapp(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_onRemoteCallCellMethodFromClient : Message
	{

		public Message_Baseapp_onRemoteCallCellMethodFromClient(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_onClientActiveTick : Message
	{

		public Message_Baseapp_onClientActiveTick(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_importClientMessages : Message
	{

		public Message_Baseapp_importClientMessages(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Baseapp_importClientEntityDef : Message
	{

		public Message_Baseapp_importClientEntityDef(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Message_Entity_onRemoteMethodCall : Message
	{

		public Message_Entity_onRemoteMethodCall(MessageID msgid, string msgname, Int16 length, sbyte argstype, List<Byte> msgargtypes):
			base(msgid, msgname, length, argstype, msgargtypes)
		{

		}

		public override void handleMessage(MemoryStream msgstream)
		{
		}
	}

	public class Messages
	{
		public static Dictionary<MessageID, Message> loginappMessages = new Dictionary<MessageID, Message>();
		public static Dictionary<MessageID, Message> baseappMessages = new Dictionary<MessageID, Message>();
		public static Dictionary<MessageID, Message> clientMessages = new Dictionary<MessageID, Message>();
		public static Dictionary<string, Message> messages = new Dictionary<string, Message>();

		public static void clear()
		{
			loginappMessages = new Dictionary<MessageID, Message>();
			baseappMessages = new Dictionary<MessageID, Message>();
			clientMessages = new Dictionary<MessageID, Message>();
			messages = new Dictionary<string, Message>();

			init();
		}


		public static bool init()
		{

			List<Byte> Client_onReloginBaseappFailed_argstypes = new List<Byte>();
			Client_onReloginBaseappFailed_argstypes.Add(3);
			Messages.messages["Client_onReloginBaseappFailed"] = new Message_Client_onReloginBaseappFailed(8, "Client_onReloginBaseappFailed", 2, 0, Client_onReloginBaseappFailed_argstypes);
			Messages.clientMessages[8] = Messages.messages["Client_onReloginBaseappFailed"];

			Messages.messages["Client_onEntityLeaveWorldOptimized"] = new Message_Client_onEntityLeaveWorldOptimized(9, "Client_onEntityLeaveWorldOptimized", -1, -1, new List<Byte>());
			Messages.clientMessages[9] = Messages.messages["Client_onEntityLeaveWorldOptimized"];

			Messages.messages["Client_onRemoteMethodCallOptimized"] = new Message_Client_onRemoteMethodCallOptimized(10, "Client_onRemoteMethodCallOptimized", -1, -1, new List<Byte>());
			Messages.clientMessages[10] = Messages.messages["Client_onRemoteMethodCallOptimized"];

			Messages.messages["Client_onUpdatePropertysOptimized"] = new Message_Client_onUpdatePropertysOptimized(11, "Client_onUpdatePropertysOptimized", -1, -1, new List<Byte>());
			Messages.clientMessages[11] = Messages.messages["Client_onUpdatePropertysOptimized"];

			Messages.messages["Client_onSetEntityPosAndDir"] = new Message_Client_onSetEntityPosAndDir(12, "Client_onSetEntityPosAndDir", -1, -1, new List<Byte>());
			Messages.clientMessages[12] = Messages.messages["Client_onSetEntityPosAndDir"];


			List<Byte> Client_onUpdateBasePos_argstypes = new List<Byte>();
			Client_onUpdateBasePos_argstypes.Add(13);
			Client_onUpdateBasePos_argstypes.Add(13);
			Client_onUpdateBasePos_argstypes.Add(13);
			Messages.messages["Client_onUpdateBasePos"] = new Message_Client_onUpdateBasePos(13, "Client_onUpdateBasePos", 12, 0, Client_onUpdateBasePos_argstypes);
			Messages.clientMessages[13] = Messages.messages["Client_onUpdateBasePos"];

			Messages.messages["Client_onUpdateBaseDir"] = new Message_Client_onUpdateBaseDir(14, "Client_onUpdateBaseDir", -1, -1, new List<Byte>());
			Messages.clientMessages[14] = Messages.messages["Client_onUpdateBaseDir"];


			List<Byte> Client_onUpdateBasePosXZ_argstypes = new List<Byte>();
			Client_onUpdateBasePosXZ_argstypes.Add(13);
			Client_onUpdateBasePosXZ_argstypes.Add(13);
			Messages.messages["Client_onUpdateBasePosXZ"] = new Message_Client_onUpdateBasePosXZ(15, "Client_onUpdateBasePosXZ", 8, 0, Client_onUpdateBasePosXZ_argstypes);
			Messages.clientMessages[15] = Messages.messages["Client_onUpdateBasePosXZ"];

			Messages.messages["Client_onUpdateData"] = new Message_Client_onUpdateData(16, "Client_onUpdateData", -1, -1, new List<Byte>());
			Messages.clientMessages[16] = Messages.messages["Client_onUpdateData"];

			Messages.messages["Client_onUpdateData_ypr"] = new Message_Client_onUpdateData_ypr(17, "Client_onUpdateData_ypr", -1, -1, new List<Byte>());
			Messages.clientMessages[17] = Messages.messages["Client_onUpdateData_ypr"];

			Messages.messages["Client_onUpdateData_yp"] = new Message_Client_onUpdateData_yp(18, "Client_onUpdateData_yp", -1, -1, new List<Byte>());
			Messages.clientMessages[18] = Messages.messages["Client_onUpdateData_yp"];

			Messages.messages["Client_onUpdateData_yr"] = new Message_Client_onUpdateData_yr(19, "Client_onUpdateData_yr", -1, -1, new List<Byte>());
			Messages.clientMessages[19] = Messages.messages["Client_onUpdateData_yr"];

			Messages.messages["Client_onUpdateData_pr"] = new Message_Client_onUpdateData_pr(20, "Client_onUpdateData_pr", -1, -1, new List<Byte>());
			Messages.clientMessages[20] = Messages.messages["Client_onUpdateData_pr"];

			Messages.messages["Client_onUpdateData_y"] = new Message_Client_onUpdateData_y(21, "Client_onUpdateData_y", -1, -1, new List<Byte>());
			Messages.clientMessages[21] = Messages.messages["Client_onUpdateData_y"];

			Messages.messages["Client_onUpdateData_p"] = new Message_Client_onUpdateData_p(22, "Client_onUpdateData_p", -1, -1, new List<Byte>());
			Messages.clientMessages[22] = Messages.messages["Client_onUpdateData_p"];

			Messages.messages["Client_onUpdateData_r"] = new Message_Client_onUpdateData_r(23, "Client_onUpdateData_r", -1, -1, new List<Byte>());
			Messages.clientMessages[23] = Messages.messages["Client_onUpdateData_r"];

			Messages.messages["Client_onUpdateData_xz"] = new Message_Client_onUpdateData_xz(24, "Client_onUpdateData_xz", -1, -1, new List<Byte>());
			Messages.clientMessages[24] = Messages.messages["Client_onUpdateData_xz"];

			Messages.messages["Client_onUpdateData_xz_ypr"] = new Message_Client_onUpdateData_xz_ypr(25, "Client_onUpdateData_xz_ypr", -1, -1, new List<Byte>());
			Messages.clientMessages[25] = Messages.messages["Client_onUpdateData_xz_ypr"];

			Messages.messages["Client_onUpdateData_xz_yp"] = new Message_Client_onUpdateData_xz_yp(26, "Client_onUpdateData_xz_yp", -1, -1, new List<Byte>());
			Messages.clientMessages[26] = Messages.messages["Client_onUpdateData_xz_yp"];

			Messages.messages["Client_onUpdateData_xz_yr"] = new Message_Client_onUpdateData_xz_yr(27, "Client_onUpdateData_xz_yr", -1, -1, new List<Byte>());
			Messages.clientMessages[27] = Messages.messages["Client_onUpdateData_xz_yr"];

			Messages.messages["Client_onUpdateData_xz_pr"] = new Message_Client_onUpdateData_xz_pr(28, "Client_onUpdateData_xz_pr", -1, -1, new List<Byte>());
			Messages.clientMessages[28] = Messages.messages["Client_onUpdateData_xz_pr"];

			Messages.messages["Client_onUpdateData_xz_y"] = new Message_Client_onUpdateData_xz_y(29, "Client_onUpdateData_xz_y", -1, -1, new List<Byte>());
			Messages.clientMessages[29] = Messages.messages["Client_onUpdateData_xz_y"];

			Messages.messages["Client_onUpdateData_xz_p"] = new Message_Client_onUpdateData_xz_p(30, "Client_onUpdateData_xz_p", -1, -1, new List<Byte>());
			Messages.clientMessages[30] = Messages.messages["Client_onUpdateData_xz_p"];

			Messages.messages["Client_onUpdateData_xz_r"] = new Message_Client_onUpdateData_xz_r(31, "Client_onUpdateData_xz_r", -1, -1, new List<Byte>());
			Messages.clientMessages[31] = Messages.messages["Client_onUpdateData_xz_r"];

			Messages.messages["Client_onUpdateData_xyz"] = new Message_Client_onUpdateData_xyz(32, "Client_onUpdateData_xyz", -1, -1, new List<Byte>());
			Messages.clientMessages[32] = Messages.messages["Client_onUpdateData_xyz"];

			Messages.messages["Client_onUpdateData_xyz_ypr"] = new Message_Client_onUpdateData_xyz_ypr(33, "Client_onUpdateData_xyz_ypr", -1, -1, new List<Byte>());
			Messages.clientMessages[33] = Messages.messages["Client_onUpdateData_xyz_ypr"];

			Messages.messages["Client_onUpdateData_xyz_yp"] = new Message_Client_onUpdateData_xyz_yp(34, "Client_onUpdateData_xyz_yp", -1, -1, new List<Byte>());
			Messages.clientMessages[34] = Messages.messages["Client_onUpdateData_xyz_yp"];

			Messages.messages["Client_onUpdateData_xyz_yr"] = new Message_Client_onUpdateData_xyz_yr(35, "Client_onUpdateData_xyz_yr", -1, -1, new List<Byte>());
			Messages.clientMessages[35] = Messages.messages["Client_onUpdateData_xyz_yr"];

			Messages.messages["Client_onUpdateData_xyz_pr"] = new Message_Client_onUpdateData_xyz_pr(36, "Client_onUpdateData_xyz_pr", -1, -1, new List<Byte>());
			Messages.clientMessages[36] = Messages.messages["Client_onUpdateData_xyz_pr"];

			Messages.messages["Client_onUpdateData_xyz_y"] = new Message_Client_onUpdateData_xyz_y(37, "Client_onUpdateData_xyz_y", -1, -1, new List<Byte>());
			Messages.clientMessages[37] = Messages.messages["Client_onUpdateData_xyz_y"];

			Messages.messages["Client_onUpdateData_xyz_p"] = new Message_Client_onUpdateData_xyz_p(38, "Client_onUpdateData_xyz_p", -1, -1, new List<Byte>());
			Messages.clientMessages[38] = Messages.messages["Client_onUpdateData_xyz_p"];

			Messages.messages["Client_onUpdateData_xyz_r"] = new Message_Client_onUpdateData_xyz_r(39, "Client_onUpdateData_xyz_r", -1, -1, new List<Byte>());
			Messages.clientMessages[39] = Messages.messages["Client_onUpdateData_xyz_r"];

			Messages.messages["Client_onUpdateData_ypr_optimized"] = new Message_Client_onUpdateData_ypr_optimized(40, "Client_onUpdateData_ypr_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[40] = Messages.messages["Client_onUpdateData_ypr_optimized"];

			Messages.messages["Client_onUpdateData_yp_optimized"] = new Message_Client_onUpdateData_yp_optimized(41, "Client_onUpdateData_yp_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[41] = Messages.messages["Client_onUpdateData_yp_optimized"];

			Messages.messages["Client_onUpdateData_yr_optimized"] = new Message_Client_onUpdateData_yr_optimized(42, "Client_onUpdateData_yr_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[42] = Messages.messages["Client_onUpdateData_yr_optimized"];

			Messages.messages["Client_onUpdateData_pr_optimized"] = new Message_Client_onUpdateData_pr_optimized(43, "Client_onUpdateData_pr_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[43] = Messages.messages["Client_onUpdateData_pr_optimized"];

			Messages.messages["Client_onUpdateData_y_optimized"] = new Message_Client_onUpdateData_y_optimized(44, "Client_onUpdateData_y_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[44] = Messages.messages["Client_onUpdateData_y_optimized"];

			Messages.messages["Client_onUpdateData_p_optimized"] = new Message_Client_onUpdateData_p_optimized(45, "Client_onUpdateData_p_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[45] = Messages.messages["Client_onUpdateData_p_optimized"];

			Messages.messages["Client_onUpdateData_r_optimized"] = new Message_Client_onUpdateData_r_optimized(46, "Client_onUpdateData_r_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[46] = Messages.messages["Client_onUpdateData_r_optimized"];

			Messages.messages["Client_onUpdateData_xz_optimized"] = new Message_Client_onUpdateData_xz_optimized(47, "Client_onUpdateData_xz_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[47] = Messages.messages["Client_onUpdateData_xz_optimized"];

			Messages.messages["Client_onUpdateData_xz_ypr_optimized"] = new Message_Client_onUpdateData_xz_ypr_optimized(48, "Client_onUpdateData_xz_ypr_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[48] = Messages.messages["Client_onUpdateData_xz_ypr_optimized"];

			Messages.messages["Client_onUpdateData_xz_yp_optimized"] = new Message_Client_onUpdateData_xz_yp_optimized(49, "Client_onUpdateData_xz_yp_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[49] = Messages.messages["Client_onUpdateData_xz_yp_optimized"];

			Messages.messages["Client_onUpdateData_xz_yr_optimized"] = new Message_Client_onUpdateData_xz_yr_optimized(50, "Client_onUpdateData_xz_yr_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[50] = Messages.messages["Client_onUpdateData_xz_yr_optimized"];

			Messages.messages["Client_onUpdateData_xz_pr_optimized"] = new Message_Client_onUpdateData_xz_pr_optimized(51, "Client_onUpdateData_xz_pr_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[51] = Messages.messages["Client_onUpdateData_xz_pr_optimized"];

			Messages.messages["Client_onUpdateData_xz_y_optimized"] = new Message_Client_onUpdateData_xz_y_optimized(52, "Client_onUpdateData_xz_y_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[52] = Messages.messages["Client_onUpdateData_xz_y_optimized"];

			Messages.messages["Client_onUpdateData_xz_p_optimized"] = new Message_Client_onUpdateData_xz_p_optimized(53, "Client_onUpdateData_xz_p_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[53] = Messages.messages["Client_onUpdateData_xz_p_optimized"];

			Messages.messages["Client_onUpdateData_xz_r_optimized"] = new Message_Client_onUpdateData_xz_r_optimized(54, "Client_onUpdateData_xz_r_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[54] = Messages.messages["Client_onUpdateData_xz_r_optimized"];

			Messages.messages["Client_onUpdateData_xyz_optimized"] = new Message_Client_onUpdateData_xyz_optimized(55, "Client_onUpdateData_xyz_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[55] = Messages.messages["Client_onUpdateData_xyz_optimized"];

			Messages.messages["Client_onUpdateData_xyz_ypr_optimized"] = new Message_Client_onUpdateData_xyz_ypr_optimized(56, "Client_onUpdateData_xyz_ypr_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[56] = Messages.messages["Client_onUpdateData_xyz_ypr_optimized"];

			Messages.messages["Client_onUpdateData_xyz_yp_optimized"] = new Message_Client_onUpdateData_xyz_yp_optimized(57, "Client_onUpdateData_xyz_yp_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[57] = Messages.messages["Client_onUpdateData_xyz_yp_optimized"];

			Messages.messages["Client_onUpdateData_xyz_yr_optimized"] = new Message_Client_onUpdateData_xyz_yr_optimized(58, "Client_onUpdateData_xyz_yr_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[58] = Messages.messages["Client_onUpdateData_xyz_yr_optimized"];

			Messages.messages["Client_onUpdateData_xyz_pr_optimized"] = new Message_Client_onUpdateData_xyz_pr_optimized(59, "Client_onUpdateData_xyz_pr_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[59] = Messages.messages["Client_onUpdateData_xyz_pr_optimized"];

			Messages.messages["Client_onUpdateData_xyz_y_optimized"] = new Message_Client_onUpdateData_xyz_y_optimized(60, "Client_onUpdateData_xyz_y_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[60] = Messages.messages["Client_onUpdateData_xyz_y_optimized"];

			Messages.messages["Client_onUpdateData_xyz_p_optimized"] = new Message_Client_onUpdateData_xyz_p_optimized(61, "Client_onUpdateData_xyz_p_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[61] = Messages.messages["Client_onUpdateData_xyz_p_optimized"];

			Messages.messages["Client_onUpdateData_xyz_r_optimized"] = new Message_Client_onUpdateData_xyz_r_optimized(62, "Client_onUpdateData_xyz_r_optimized", -1, -1, new List<Byte>());
			Messages.clientMessages[62] = Messages.messages["Client_onUpdateData_xyz_r_optimized"];

			Messages.messages["Client_onImportServerErrorsDescr"] = new Message_Client_onImportServerErrorsDescr(63, "Client_onImportServerErrorsDescr", -1, -1, new List<Byte>());
			Messages.clientMessages[63] = Messages.messages["Client_onImportServerErrorsDescr"];

			Messages.messages["Client_onImportClientSDK"] = new Message_Client_onImportClientSDK(64, "Client_onImportClientSDK", -1, -1, new List<Byte>());
			Messages.clientMessages[64] = Messages.messages["Client_onImportClientSDK"];

			Messages.messages["Client_initSpaceData"] = new Message_Client_initSpaceData(65, "Client_initSpaceData", -1, -1, new List<Byte>());
			Messages.clientMessages[65] = Messages.messages["Client_initSpaceData"];


			List<Byte> Client_setSpaceData_argstypes = new List<Byte>();
			Client_setSpaceData_argstypes.Add(4);
			Client_setSpaceData_argstypes.Add(1);
			Client_setSpaceData_argstypes.Add(1);
			Messages.messages["Client_setSpaceData"] = new Message_Client_setSpaceData(66, "Client_setSpaceData", -1, 0, Client_setSpaceData_argstypes);
			Messages.clientMessages[66] = Messages.messages["Client_setSpaceData"];


			List<Byte> Client_delSpaceData_argstypes = new List<Byte>();
			Client_delSpaceData_argstypes.Add(4);
			Client_delSpaceData_argstypes.Add(1);
			Messages.messages["Client_delSpaceData"] = new Message_Client_delSpaceData(67, "Client_delSpaceData", -1, 0, Client_delSpaceData_argstypes);
			Messages.clientMessages[67] = Messages.messages["Client_delSpaceData"];


			List<Byte> Client_onReqAccountResetPasswordCB_argstypes = new List<Byte>();
			Client_onReqAccountResetPasswordCB_argstypes.Add(3);
			Messages.messages["Client_onReqAccountResetPasswordCB"] = new Message_Client_onReqAccountResetPasswordCB(68, "Client_onReqAccountResetPasswordCB", 2, 0, Client_onReqAccountResetPasswordCB_argstypes);
			Messages.clientMessages[68] = Messages.messages["Client_onReqAccountResetPasswordCB"];


			List<Byte> Client_onReqAccountBindEmailCB_argstypes = new List<Byte>();
			Client_onReqAccountBindEmailCB_argstypes.Add(3);
			Messages.messages["Client_onReqAccountBindEmailCB"] = new Message_Client_onReqAccountBindEmailCB(69, "Client_onReqAccountBindEmailCB", 2, 0, Client_onReqAccountBindEmailCB_argstypes);
			Messages.clientMessages[69] = Messages.messages["Client_onReqAccountBindEmailCB"];


			List<Byte> Client_onReqAccountNewPasswordCB_argstypes = new List<Byte>();
			Client_onReqAccountNewPasswordCB_argstypes.Add(3);
			Messages.messages["Client_onReqAccountNewPasswordCB"] = new Message_Client_onReqAccountNewPasswordCB(70, "Client_onReqAccountNewPasswordCB", 2, 0, Client_onReqAccountNewPasswordCB_argstypes);
			Messages.clientMessages[70] = Messages.messages["Client_onReqAccountNewPasswordCB"];

			Messages.messages["Client_onReloginBaseappSuccessfully"] = new Message_Client_onReloginBaseappSuccessfully(71, "Client_onReloginBaseappSuccessfully", -1, -1, new List<Byte>());
			Messages.clientMessages[71] = Messages.messages["Client_onReloginBaseappSuccessfully"];

			Messages.messages["Client_onAppActiveTickCB"] = new Message_Client_onAppActiveTickCB(72, "Client_onAppActiveTickCB", 0, 0, new List<Byte>());
			Messages.clientMessages[72] = Messages.messages["Client_onAppActiveTickCB"];

			Messages.messages["Client_onCreateAccountResult"] = new Message_Client_onCreateAccountResult(501, "Client_onCreateAccountResult", -1, -1, new List<Byte>());
			Messages.clientMessages[501] = Messages.messages["Client_onCreateAccountResult"];

			Messages.messages["Client_onLoginSuccessfully"] = new Message_Client_onLoginSuccessfully(502, "Client_onLoginSuccessfully", -1, -1, new List<Byte>());
			Messages.clientMessages[502] = Messages.messages["Client_onLoginSuccessfully"];

			Messages.messages["Client_onLoginFailed"] = new Message_Client_onLoginFailed(503, "Client_onLoginFailed", -1, -1, new List<Byte>());
			Messages.clientMessages[503] = Messages.messages["Client_onLoginFailed"];


			List<Byte> Client_onCreatedProxies_argstypes = new List<Byte>();
			Client_onCreatedProxies_argstypes.Add(5);
			Client_onCreatedProxies_argstypes.Add(8);
			Client_onCreatedProxies_argstypes.Add(1);
			Messages.messages["Client_onCreatedProxies"] = new Message_Client_onCreatedProxies(504, "Client_onCreatedProxies", -1, 0, Client_onCreatedProxies_argstypes);
			Messages.clientMessages[504] = Messages.messages["Client_onCreatedProxies"];


			List<Byte> Client_onLoginBaseappFailed_argstypes = new List<Byte>();
			Client_onLoginBaseappFailed_argstypes.Add(3);
			Messages.messages["Client_onLoginBaseappFailed"] = new Message_Client_onLoginBaseappFailed(505, "Client_onLoginBaseappFailed", 2, 0, Client_onLoginBaseappFailed_argstypes);
			Messages.clientMessages[505] = Messages.messages["Client_onLoginBaseappFailed"];

			Messages.messages["Client_onRemoteMethodCall"] = new Message_Client_onRemoteMethodCall(506, "Client_onRemoteMethodCall", -1, -1, new List<Byte>());
			Messages.clientMessages[506] = Messages.messages["Client_onRemoteMethodCall"];

			Messages.messages["Client_onEntityEnterWorld"] = new Message_Client_onEntityEnterWorld(507, "Client_onEntityEnterWorld", -1, -1, new List<Byte>());
			Messages.clientMessages[507] = Messages.messages["Client_onEntityEnterWorld"];


			List<Byte> Client_onEntityLeaveWorld_argstypes = new List<Byte>();
			Client_onEntityLeaveWorld_argstypes.Add(8);
			Messages.messages["Client_onEntityLeaveWorld"] = new Message_Client_onEntityLeaveWorld(508, "Client_onEntityLeaveWorld", 4, 0, Client_onEntityLeaveWorld_argstypes);
			Messages.clientMessages[508] = Messages.messages["Client_onEntityLeaveWorld"];

			Messages.messages["Client_onEntityEnterSpace"] = new Message_Client_onEntityEnterSpace(509, "Client_onEntityEnterSpace", -1, -1, new List<Byte>());
			Messages.clientMessages[509] = Messages.messages["Client_onEntityEnterSpace"];


			List<Byte> Client_onEntityLeaveSpace_argstypes = new List<Byte>();
			Client_onEntityLeaveSpace_argstypes.Add(8);
			Messages.messages["Client_onEntityLeaveSpace"] = new Message_Client_onEntityLeaveSpace(510, "Client_onEntityLeaveSpace", 4, 0, Client_onEntityLeaveSpace_argstypes);
			Messages.clientMessages[510] = Messages.messages["Client_onEntityLeaveSpace"];

			Messages.messages["Client_onUpdatePropertys"] = new Message_Client_onUpdatePropertys(511, "Client_onUpdatePropertys", -1, -1, new List<Byte>());
			Messages.clientMessages[511] = Messages.messages["Client_onUpdatePropertys"];


			List<Byte> Client_onEntityDestroyed_argstypes = new List<Byte>();
			Client_onEntityDestroyed_argstypes.Add(8);
			Messages.messages["Client_onEntityDestroyed"] = new Message_Client_onEntityDestroyed(512, "Client_onEntityDestroyed", 4, 0, Client_onEntityDestroyed_argstypes);
			Messages.clientMessages[512] = Messages.messages["Client_onEntityDestroyed"];


			List<Byte> Client_onStreamDataStarted_argstypes = new List<Byte>();
			Client_onStreamDataStarted_argstypes.Add(7);
			Client_onStreamDataStarted_argstypes.Add(4);
			Client_onStreamDataStarted_argstypes.Add(1);
			Messages.messages["Client_onStreamDataStarted"] = new Message_Client_onStreamDataStarted(514, "Client_onStreamDataStarted", -1, 0, Client_onStreamDataStarted_argstypes);
			Messages.clientMessages[514] = Messages.messages["Client_onStreamDataStarted"];

			Messages.messages["Client_onStreamDataRecv"] = new Message_Client_onStreamDataRecv(515, "Client_onStreamDataRecv", -1, -1, new List<Byte>());
			Messages.clientMessages[515] = Messages.messages["Client_onStreamDataRecv"];


			List<Byte> Client_onStreamDataCompleted_argstypes = new List<Byte>();
			Client_onStreamDataCompleted_argstypes.Add(7);
			Messages.messages["Client_onStreamDataCompleted"] = new Message_Client_onStreamDataCompleted(516, "Client_onStreamDataCompleted", 2, 0, Client_onStreamDataCompleted_argstypes);
			Messages.clientMessages[516] = Messages.messages["Client_onStreamDataCompleted"];


			List<Byte> Client_onKicked_argstypes = new List<Byte>();
			Client_onKicked_argstypes.Add(3);
			Messages.messages["Client_onKicked"] = new Message_Client_onKicked(517, "Client_onKicked", 2, 0, Client_onKicked_argstypes);
			Messages.clientMessages[517] = Messages.messages["Client_onKicked"];

			Messages.messages["Client_onImportClientMessages"] = new Message_Client_onImportClientMessages(518, "Client_onImportClientMessages", -1, -1, new List<Byte>());
			Messages.clientMessages[518] = Messages.messages["Client_onImportClientMessages"];

			Messages.messages["Client_onImportClientEntityDef"] = new Message_Client_onImportClientEntityDef(519, "Client_onImportClientEntityDef", -1, -1, new List<Byte>());
			Messages.clientMessages[519] = Messages.messages["Client_onImportClientEntityDef"];

			Messages.messages["Client_onHelloCB"] = new Message_Client_onHelloCB(521, "Client_onHelloCB", -1, -1, new List<Byte>());
			Messages.clientMessages[521] = Messages.messages["Client_onHelloCB"];

			Messages.messages["Client_onScriptVersionNotMatch"] = new Message_Client_onScriptVersionNotMatch(522, "Client_onScriptVersionNotMatch", -1, -1, new List<Byte>());
			Messages.clientMessages[522] = Messages.messages["Client_onScriptVersionNotMatch"];

			Messages.messages["Client_onVersionNotMatch"] = new Message_Client_onVersionNotMatch(523, "Client_onVersionNotMatch", -1, -1, new List<Byte>());
			Messages.clientMessages[523] = Messages.messages["Client_onVersionNotMatch"];


			List<Byte> Client_onControlEntity_argstypes = new List<Byte>();
			Client_onControlEntity_argstypes.Add(8);
			Client_onControlEntity_argstypes.Add(6);
			Messages.messages["Client_onControlEntity"] = new Message_Client_onControlEntity(524, "Client_onControlEntity", 5, 0, Client_onControlEntity_argstypes);
			Messages.clientMessages[524] = Messages.messages["Client_onControlEntity"];

			Messages.messages["Loginapp_reqCreateAccount"] = new Message_Loginapp_reqCreateAccount(2, "Loginapp_reqCreateAccount", -1, 0, new List<Byte>());
			Messages.loginappMessages[2] = Messages.messages["Loginapp_reqCreateAccount"];

			Messages.messages["Loginapp_login"] = new Message_Loginapp_login(3, "Loginapp_login", -1, 0, new List<Byte>());
			Messages.loginappMessages[3] = Messages.messages["Loginapp_login"];

			Messages.messages["Loginapp_hello"] = new Message_Loginapp_hello(4, "Loginapp_hello", -1, 0, new List<Byte>());
			Messages.loginappMessages[4] = Messages.messages["Loginapp_hello"];

			Messages.messages["Loginapp_importClientMessages"] = new Message_Loginapp_importClientMessages(5, "Loginapp_importClientMessages", 0, 0, new List<Byte>());
			Messages.loginappMessages[5] = Messages.messages["Loginapp_importClientMessages"];

			Messages.messages["Loginapp_reqCreateMailAccount"] = new Message_Loginapp_reqCreateMailAccount(6, "Loginapp_reqCreateMailAccount", -1, 0, new List<Byte>());
			Messages.loginappMessages[6] = Messages.messages["Loginapp_reqCreateMailAccount"];

			Messages.messages["Loginapp_importClientSDK"] = new Message_Loginapp_importClientSDK(7, "Loginapp_importClientSDK", -1, 0, new List<Byte>());
			Messages.loginappMessages[7] = Messages.messages["Loginapp_importClientSDK"];

			Messages.messages["Loginapp_importServerErrorsDescr"] = new Message_Loginapp_importServerErrorsDescr(8, "Loginapp_importServerErrorsDescr", 0, 0, new List<Byte>());
			Messages.loginappMessages[8] = Messages.messages["Loginapp_importServerErrorsDescr"];

			Messages.messages["Loginapp_onClientActiveTick"] = new Message_Loginapp_onClientActiveTick(11, "Loginapp_onClientActiveTick", 0, 0, new List<Byte>());
			Messages.loginappMessages[11] = Messages.messages["Loginapp_onClientActiveTick"];


			List<Byte> Loginapp_reqAccountResetPassword_argstypes = new List<Byte>();
			Loginapp_reqAccountResetPassword_argstypes.Add(1);
			Messages.messages["Loginapp_reqAccountResetPassword"] = new Message_Loginapp_reqAccountResetPassword(12, "Loginapp_reqAccountResetPassword", -1, 0, Loginapp_reqAccountResetPassword_argstypes);
			Messages.loginappMessages[12] = Messages.messages["Loginapp_reqAccountResetPassword"];


			List<Byte> Baseapp_logoutBaseapp_argstypes = new List<Byte>();
			Baseapp_logoutBaseapp_argstypes.Add(5);
			Baseapp_logoutBaseapp_argstypes.Add(8);
			Messages.messages["Baseapp_logoutBaseapp"] = new Message_Baseapp_logoutBaseapp(24, "Baseapp_logoutBaseapp", 12, 0, Baseapp_logoutBaseapp_argstypes);
			Messages.baseappMessages[24] = Messages.messages["Baseapp_logoutBaseapp"];

			Messages.messages["Baseapp_onUpdateDataFromClient"] = new Message_Baseapp_onUpdateDataFromClient(27, "Baseapp_onUpdateDataFromClient", -1, -1, new List<Byte>());
			Messages.baseappMessages[27] = Messages.messages["Baseapp_onUpdateDataFromClient"];

			Messages.messages["Baseapp_onUpdateDataFromClientForControlledEntity"] = new Message_Baseapp_onUpdateDataFromClientForControlledEntity(28, "Baseapp_onUpdateDataFromClientForControlledEntity", -1, -1, new List<Byte>());
			Messages.baseappMessages[28] = Messages.messages["Baseapp_onUpdateDataFromClientForControlledEntity"];


			List<Byte> Baseapp_reqAccountBindEmail_argstypes = new List<Byte>();
			Baseapp_reqAccountBindEmail_argstypes.Add(8);
			Baseapp_reqAccountBindEmail_argstypes.Add(1);
			Baseapp_reqAccountBindEmail_argstypes.Add(1);
			Messages.messages["Baseapp_reqAccountBindEmail"] = new Message_Baseapp_reqAccountBindEmail(50, "Baseapp_reqAccountBindEmail", -1, 0, Baseapp_reqAccountBindEmail_argstypes);
			Messages.baseappMessages[50] = Messages.messages["Baseapp_reqAccountBindEmail"];


			List<Byte> Baseapp_reqAccountNewPassword_argstypes = new List<Byte>();
			Baseapp_reqAccountNewPassword_argstypes.Add(8);
			Baseapp_reqAccountNewPassword_argstypes.Add(1);
			Baseapp_reqAccountNewPassword_argstypes.Add(1);
			Messages.messages["Baseapp_reqAccountNewPassword"] = new Message_Baseapp_reqAccountNewPassword(53, "Baseapp_reqAccountNewPassword", -1, 0, Baseapp_reqAccountNewPassword_argstypes);
			Messages.baseappMessages[53] = Messages.messages["Baseapp_reqAccountNewPassword"];

			Messages.messages["Entity_forwardEntityMessageToCellappFromClient"] = new Message_Entity_forwardEntityMessageToCellappFromClient(57, "Entity_forwardEntityMessageToCellappFromClient", -1, -1, new List<Byte>());
			Messages.baseappMessages[57] = Messages.messages["Entity_forwardEntityMessageToCellappFromClient"];

			Messages.messages["Baseapp_hello"] = new Message_Baseapp_hello(200, "Baseapp_hello", -1, -1, new List<Byte>());
			Messages.baseappMessages[200] = Messages.messages["Baseapp_hello"];


			List<Byte> Baseapp_loginBaseapp_argstypes = new List<Byte>();
			Baseapp_loginBaseapp_argstypes.Add(1);
			Baseapp_loginBaseapp_argstypes.Add(1);
			Messages.messages["Baseapp_loginBaseapp"] = new Message_Baseapp_loginBaseapp(202, "Baseapp_loginBaseapp", -1, 0, Baseapp_loginBaseapp_argstypes);
			Messages.baseappMessages[202] = Messages.messages["Baseapp_loginBaseapp"];


			List<Byte> Baseapp_reloginBaseapp_argstypes = new List<Byte>();
			Baseapp_reloginBaseapp_argstypes.Add(1);
			Baseapp_reloginBaseapp_argstypes.Add(1);
			Baseapp_reloginBaseapp_argstypes.Add(5);
			Baseapp_reloginBaseapp_argstypes.Add(8);
			Messages.messages["Baseapp_reloginBaseapp"] = new Message_Baseapp_reloginBaseapp(204, "Baseapp_reloginBaseapp", -1, 0, Baseapp_reloginBaseapp_argstypes);
			Messages.baseappMessages[204] = Messages.messages["Baseapp_reloginBaseapp"];

			Messages.messages["Baseapp_onRemoteCallCellMethodFromClient"] = new Message_Baseapp_onRemoteCallCellMethodFromClient(205, "Baseapp_onRemoteCallCellMethodFromClient", -1, -1, new List<Byte>());
			Messages.baseappMessages[205] = Messages.messages["Baseapp_onRemoteCallCellMethodFromClient"];

			Messages.messages["Baseapp_onClientActiveTick"] = new Message_Baseapp_onClientActiveTick(206, "Baseapp_onClientActiveTick", 0, 0, new List<Byte>());
			Messages.baseappMessages[206] = Messages.messages["Baseapp_onClientActiveTick"];

			Messages.messages["Baseapp_importClientMessages"] = new Message_Baseapp_importClientMessages(207, "Baseapp_importClientMessages", 0, 0, new List<Byte>());
			Messages.baseappMessages[207] = Messages.messages["Baseapp_importClientMessages"];

			Messages.messages["Baseapp_importClientEntityDef"] = new Message_Baseapp_importClientEntityDef(208, "Baseapp_importClientEntityDef", 0, 0, new List<Byte>());
			Messages.baseappMessages[208] = Messages.messages["Baseapp_importClientEntityDef"];

			Messages.messages["Entity_onRemoteMethodCall"] = new Message_Entity_onRemoteMethodCall(302, "Entity_onRemoteMethodCall", -1, -1, new List<Byte>());
			Messages.baseappMessages[302] = Messages.messages["Entity_onRemoteMethodCall"];


			return true;
		}
	}
}